### ISSUE TITLE
Reorganize test suite

### ISSUE THREAD

**Issue by bakpakin** [janet-lang/janet#1154]
Janet's test suite is hard to navigate and disorganized. The coverage is fairly broad and good for catching most serious regressions, but it is not obvious where to put new tests - Better organization is needed in the long term.

One way would to be to break up the suites by module.

**Comment by pepe** [comment]
I come to that organization in my codes.

**Comment by tionis** [comment]
I also think that naming tests after modules would be very useful. (In general, so for spork too).
Every time I add a new test, I have to grep to find a fitting suite.

Perhaps an argument could be added to `jpm test` to specify which suite to execute. (Even though it brings no real benefit over janet test/some-module.janet` as far as I can see)

**Comment by sogaiu** [comment]
To get some sense of what might be involved, I tried splitting `suite0000.janet` up.

[Here](https://github.com/sogaiu/janet/commit/2a34a10d971e25573edea3ec6838c38a2700a2ea) is a commit with an attempt.

Some things that happened:

* Changed `helper.janet` so it can work with a string instead of a number (`suite-name` instead of `suite-number`)
* Temporarily named new files `suite-<module-name>.janet` -- this was to work with the existing `Makefile`
* I tried to place tests in a file associated with what I guessed was the most relevant module (e.g. `not` is actually defined in `math.c` so [this line](https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/test/suite0000.janet#L63) and [this line](https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/test/suite0000.janet#L65) end up in `suite-math.janet`) -- but see below for more on these lines.
* Some tests that had lines interleaved got split up -- e.g. there were [some lines for structs and tables that were together](https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/test/suite0000.janet#L313-L328), but as a test (no pun intended), I moved one set of lines to a file for structs and the remaining set of lines to a file for tables
* Changed some names (e.g. [here](https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/test/suite0000.janet#L227) the name `merge` is used, but I think this could potentially shadow an actual use of the built-in `merge` at some point so it seemed better to rename for future-proofing) [1]
* Added comments in a few places (e.g. [here](https://github.com/sogaiu/janet/commit/2a34a10d971e25573edea3ec6838c38a2700a2ea#diff-faf55629d151fdeceb1ce33950b008c990fe29e99d8bff6d3263714ee2379435R49) is an explanatory comment with an abbreviated commit hash that added it [2])
* Wasn't clear to me where some stuff should go so for the moment I made a file named `suite-unknown.janet`.  For example, may be [this line](https://github.com/janet-lang/janet/blob/master/test/suite0000.janet#L64) should end up in `suite-parse.janet` because of [this code](https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/src/core/parse.c#L468), but the lines above it and below it refer to `false` and `nil` in the context of `not`.  So may be they should all go in `suite-parse.janet` (given the explanatory comments for all three lines) instead of what I had chosen for those two lines (i.e. `suite-math.janet`).  A less obvious case might be [these lines](https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/test/suite0000.janet#L71-L77).

Other things:

* Change some line lengths for width-challenged situations
* Possibly [these lines](https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/test/suite0000.janet#L322-L323) should have `(/ 0 0)` instead of `nil`

---

[1] [`rjan`](https://github.com/sogaiu/review-janet) - an experimental linter - noticed this :)
[2] Commit hash info seems like the kind of thing you can't always add because it doesn't always exist at the time one is expressing the comment -- and perhaps people would find this to be too much to do.  This was just an experiment in any case.

**Comment by sogaiu** [comment]
I've made a pass through some more files on [this branch](https://github.com/sogaiu/janet/tree/reorganize-tests).

There are additional commits for splitting the following `suite00*.janet` files:

* [suite0001.janet](https://github.com/sogaiu/janet/commit/97e7e59932963e11622f08dd5181bd60bf7437ab)
* [suite0002.janet](https://github.com/sogaiu/janet/commit/6dd23e362ca885976c5402b809d83bb300a32a4e)
* [suite0003.janet](https://github.com/sogaiu/janet/commit/937e779a234e552b788a72f1ec09ad28a301c15f)
* [suite0004.janet](https://github.com/sogaiu/janet/commit/bc2fb5687ab511f01429609ce43d99d9f4c5b08a)

I didn't mention this before, but there is also a `suite-boot.janet` file as some content seemed like a better fit for that than what lives under `src/core/`.

**Comment by sogaiu** [comment]
Here are a few more observations having done a bit more:

* To try to determine a specific file to put a test in, what I do now is:
  * First check blame info for the `suite00XY.janet` file the test is in.  This results in a commit that may be the initial commit code was added.  Sometimes one has to keep tracing history to reach a commit where test code was added.
  * Once one has reached the "original" commit, looking at what other files were changed in the same commit can be helpful in getting a sense of which `suite-*.janet` file to place the test in.  Sometimes it helps to go back some number of commits more as a test was not necessarily added in the same commit as the relevant code.
  * Sometimes there is more than one file that changed which seemed relevant to the test.  In such cases I've sometimes put those in `suite-unknown.janet` for the moment.  I'm thinking to go back through these later.

* It turns out that currently, it's often relatively straight-forward to identify if there was a corresponding issue for a test via the "original" commit (this is for cases where the test doesn't have a comment or description that mentions the issue).  However, once we reorganize things, I'm not sure how easy this is going to be.  I'm currently thinking of going back to identify relevant issue numbers and place them as comments for corresponding tests (if there isn't already such a comment or string -- often there is).

Once I finish one pass through, I'm thinking to go through again to attend to some of the things I mentioned above.

If there are things people would like me to look for / make note of, may be I can convince myself to do some of those things :)

**Comment by sogaiu** [comment]
Ok, I made it through once.  I updated the list of commits [here](https://github.com/janet-lang/janet/issues/1154#issuecomment-1563599282) for the curious.

I wrote a little script [1] to count the number of tests executed.

It seems there are 1847 tests before and after, which all pass ATM.

before:
<details>
<pre>
$ make test
for f in test/suite*.janet; do  ./build/janet "$f" || exit; done
Starting suite 0...
Finished suite 0 in 0.012 seconds - 190 of 190 tests passed.
Starting suite 1...
Finished suite 1 in 0.018 seconds - 158 of 158 tests passed.
Starting suite 2...
Finished suite 2 in 0.002 seconds - 136 of 136 tests passed.
Starting suite 3...
Finished suite 3 in 0.008 seconds - 188 of 188 tests passed.
Starting suite 4...
Finished suite 4 in 0.000 seconds - 26 of 26 tests passed.
Starting suite 5...
Finished suite 5 in 0.001 seconds - 55 of 55 tests passed.
Starting suite 6...
Finished suite 6 in 0.002 seconds - 105 of 105 tests passed.
Starting suite 7...
Finished suite 7 in 0.222 seconds - 220 of 220 tests passed.
Starting suite 8...
Finished suite 8 in 0.005 seconds - 130 of 130 tests passed.
Starting suite 9...
Finished suite 9 in 0.312 seconds - 493 of 493 tests passed.
Starting suite 10...
Finished suite 10 in 0.022 seconds - 96 of 96 tests passed.
Starting suite 11...
Finished suite 11 in 0.107 seconds - 23 of 23 tests passed.
Starting suite 12...
Finished suite 12 in 0.001 seconds - 12 of 12 tests passed.
Starting suite 13...
Finished suite 13 in 0.001 seconds - 5 of 5 tests passed.
Starting suite 14...
Finished suite 14 in 0.000 seconds - 4 of 4 tests passed.
Starting suite 15...
Finished suite 15 in 0.001 seconds - 6 of 6 tests passed.
for f in examples/*.janet; do  ./build/janet -k "$f"; done
</pre>
</details>

after:
<details>
<pre>
$ make test
for f in test/suite*.janet; do  ./build/janet "$f" || exit; done
Starting suite array...
Finished suite array in 0.000 seconds - 10 of 10 tests passed.
Starting suite asm...
Finished suite asm in 0.002 seconds - 4 of 4 tests passed.
Starting suite boot...
Finished suite boot in 0.011 seconds - 372 of 372 tests passed.
Starting suite buffer...
Finished suite buffer in 0.000 seconds - 28 of 28 tests passed.
Starting suite compile...
Finished suite compile in 0.000 seconds - 7 of 7 tests passed.
Starting suite corelib...
Finished suite corelib in 0.000 seconds - 47 of 47 tests passed.
Starting suite debug...
Finished suite debug in 0.000 seconds - 1 of 1 tests passed.
Starting suite ev...
Finished suite ev in 0.235 seconds - 493 of 493 tests passed.
Starting suite ffi...
Finished suite ffi in 0.001 seconds - 8 of 8 tests passed.
Starting suite inttypes...
Finished suite inttypes in 0.008 seconds - 62 of 62 tests passed.
Starting suite io...
Finished suite io in 0.001 seconds - 10 of 10 tests passed.
Starting suite marsh...
Finished suite marsh in 0.004 seconds - 55 of 55 tests passed.
Starting suite math...
Finished suite math in 0.037 seconds - 157 of 157 tests passed.
Starting suite os...
Finished suite os in 0.313 seconds - 38 of 38 tests passed.
Starting suite parse...
Finished suite parse in 0.001 seconds - 15 of 15 tests passed.
Starting suite peg...
Finished suite peg in 0.009 seconds - 185 of 185 tests passed.
Starting suite specials...
Finished suite specials in 0.001 seconds - 56 of 56 tests passed.
Starting suite string...
Finished suite string in 0.001 seconds - 68 of 68 tests passed.
Starting suite strtod...
Finished suite strtod in 0.000 seconds - 4 of 4 tests passed.
Starting suite struct...
Finished suite struct in 0.000 seconds - 11 of 11 tests passed.
Starting suite symcache...
Finished suite symcache in 0.001 seconds - 3 of 3 tests passed.
Starting suite table...
Finished suite table in 0.000 seconds - 14 of 14 tests passed.
Starting suite tuple...
Finished suite tuple in 0.000 seconds - 5 of 5 tests passed.
Starting suite unknown...
Finished suite unknown in 0.011 seconds - 141 of 141 tests passed.
Starting suite value...
Finished suite value in 0.000 seconds - 18 of 18 tests passed.
Starting suite vm...
Finished suite vm in 0.002 seconds - 35 of 35 tests passed.
for f in examples/*.janet; do  ./build/janet -k "$f"; done
</pre>
</details>

So may be I didn't break too much (^^;

---

[1] In Janet with PEGs ofc!  @zevv / bakpakin's [`file/lines`](https://github.com/janet-lang/janet/pull/1157) might have been handy :)

**Comment by sogaiu** [comment]
Can't...type...fast...enough :)

On a more serious note, I'm thinking to remove the following [two lines](https://github.com/janet-lang/janet/commit/ff0d3a008#diff-f500aef9fa770aaad5dfb08e5a94ac6c760c4e16430affc0e0a5c23c8cc9287fR213-R214).

Does that seem reasonable?

Removing them doesn't seem to affect the test results.

**Comment by sogaiu** [comment]
There are some things that don't have any kind of `assert`-like construct around them and I suppose that means they won't get counted as tests by the testing machinery, e.g.

* https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/test/suite0007.janet#L262-L263
* https://github.com/janet-lang/janet/blob/909c9060809303ddb4533cf841f51e7b8694e266/test/suite0008.janet#L235-L236

Should I leave these alone?

**Comment by sogaiu** [comment]
Is there anything left to do for this issue?

The idea of feature-gating came up [here](https://github.com/janet-lang/janet/pull/1162#issuecomment-1565584655) but perhaps that or something similar could be a new issue?

**Comment by bakpakin** [comment]
The feature gating would be nice - namely address the arm/ffi issue before the next release, but that is a separate issue.

**Comment by bakpakin** [comment]
Also, thanks for all the work here everyone, this all happened a lot faster than I had hoped and we got some testing added!
