### ISSUE TITLE
API for extracting partially parsed state from parser.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#121]
Currently we are able to get what nesting level the parser is at, when implementing repls and completions it would be useful to be able to inspect the partially parsed form values themselves.

e.g. be able to inspect what the current function symbol is

**Comment by ALSchwalm** [comment]
I'm interested in implementing this. Is it acceptable to break the interface for `parser/state` or would this be another function?

Given a parser buffer of "((", I'm imagining something like:

```
> (parser/state p)
@{:wrappers "((somthing" :start 2}
```

So `start` returns the starting position of the body of the inner most s-expression (or array, string, etc). It is absent when ':wrappers' is the empty string. Alternately, it could be an array of the starting position of each 'wrapper'. Either way, returning a table here would also allow us to return more parser state info in the future without breaking the interface.

I'm not sure that actually trying to return the first symbol itself is necessary, as that could sometimes be another s-expression. I'm really kind of just basing this off of emacs `parse-partial-sexp` because I'm familiar with it. Definitely open to other ideas.

**Comment by bakpakin** [comment]
I like the idea of extending `parser/state` with more info. I think it would make sense for it to take a second argument, a set of flags that indicate what state to get. If a single flag is passed, return that state value only, otherwise a table of all parser state. Also, `(parser/status p)` could be an alias for `(parser/state p :s)`. Another alternative is to use full keywords like `(os/stat)`

**Comment by ALSchwalm** [comment]
:+1: I like the idea of passing optional keywords. Currently I'm thinking of:

```
:wrappers - The current value returned by parser/state. Not sure about the name here
:start - The 'start' of the innermost s-expression (one past the opening paren, bracket, etc)
:prefix - The modifying character (if any) before the innermost s-exp (so a `'` for quoted s-expt, '@' for tables, etc)
:in-comment - Returns whether the parser is in a comment
```

Note that I haven't really looked at the difficulty of implementing these other than 'start' which is trivial. I may want to drop some of these if it would require large changes to the parser.

**Comment by bakpakin** [comment]
I don’t think any of those would require much change to the parser. However, I think the state could be much more general, such as getting the current characters in the buffer, all current values in the current form, the kind of value currently being parsed, etc.

**Comment by ALSchwalm** [comment]
That seems doable. There are a few areas where we will need to make decisions though. For example, if the parse is fed something like:

```
@{ :foo
 ```

We have an uneven number of items in the struct. I suppose we could set the value to be `nil` in this case, but that seems unwise. Maybe we just drop the incomplete key-value pair? I suspect there will be a few other situations like this. But I can go ahead and make what I think are reasonable behaviors and we can talk it out in the PR.

**Comment by bakpakin** [comment]
I think the best API is to mirror the actual state of the parser. The parser keeps a stack of already completed values called the `args` stack, which is unambiguous in terms of order and can handle even or odd numbers of table items. This is paired with another stack, the `states`  stack, which indicates what kind of form is being parsed, as well as how many values on the state stack "belong" to that state. I think for current values in a form, we should always return an array or a tuple.

For example, after

```
@{1 2 3
```

the `states` stack will contain 2 entries (state 0 is the root state, state 1 is the table state), and the `args` stack will contain 3 entries,  1, 2, and 3. After a closing `4 }`, the `states` stack will contain only the root entry, and the `args` stack will contain only the parsed table.

There is one more stack, the `buf` stack, that holds not yet completed tokens. For example, after `(def abc-`, the `states` stack will have a root state and parens tuple state, the `args` stack will be empty, and the `buf` stack will contain "abc-". Only after an end of file or non-symbol character is reached is the buf stack converted into a parsed value and put on the argstack, as a symbol, keyword, string, number, nil, true, or false. The `buf` stack is only used for "leaf" states, and is irrelevant for table, struct, array, and tuple states.

I think the `parser/state` API should mirror these states closely for full correctness. What should `parser/state` return  after `(def a @`? How about after `(def mystr "`?

All of the proposed state items (`:in-comment`, etc.) could likely be determined by looking at the top of the `states` stack, which is also much more general. I think a useful API would include some way to
convert a `JanetParseState` into a table, get the top state, get the number of states, get the nth state, etc. Checking if the parser was in a comment could be `(= ((parser/state p :top) :type) :comment)`.

**Comment by ALSchwalm** [comment]
Yep, looking at how things are laid out, that definitely makes sense. I'll see if I can get a pr in the next couple of days for this. Thanks for the info dump!
