### ISSUE TITLE
Should `reverse` on bytes return a string?

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/janet#1248]
I'm looking mainly at the asymmetry between these two forms:
```janet
> (reverse! @"abc")
@"cba"
> (reverse @"abc")
@[99 98 97]
```
Perhaps it would be more appropriate for `reverse` on a bytes to return a string? As precedent, `slice` also distinguishes between indexed and bytes similarly:
https://github.com/janet-lang/janet/blob/3a4d56afca2eee0e4dbca9a6400757d198e6d6f3/src/core/corelib.c#L412-L427
```janet
> (slice "abc" 1)
"bc"
> (slice [1 2 3] 1)
(2 3)
```

**Comment by sogaiu** [comment]
As a factor for consideration, please note the existence of `string/reverse`:

```
$ janet
Janet 1.30.0-ecc4d80a linux/x64/gcc - '(doc)' for help
repl:1:> (string/reverse @"hello")
"olleh"
repl:2:> (string/reverse "hello")
"olleh"
repl:3:> (string/reverse :hello)
"olleh"
repl:4:> (string/reverse 'hello)
"olleh"
```

**Comment by primo-ppcg** [comment]
> As a factor for consideration, please note the existence of `string/reverse`:

`string/slice` does as well.

**Comment by CosmicToast** [comment]
I think I've mentioned this before, but probably a Janet 2.0.0 would be desirable eventually.
That would allow a redesign of the stdlib (which has many more inconsistencies than just the above naming), and potentially introduce some features that are currently rather unfortunate (such as jpm being unable to perform executable builds optimally, major version compatibility checks, etc).

**Comment by sogaiu** [comment]
For reference, some past discussion: https://github.com/janet-lang/janet/issues/626

I think collecting candidate things could be useful for more than one reason.  One being that it might give a better sense of the size / impact.

---

Partly in jest, I recently realized that Janet's versioning is much more similar to Lua's than other things :)

**Comment by primo-ppcg** [comment]
> For reference, some past discussion: #626

Thanks for that, a lot of very sensible opinions. I've also concluded that no action is necessary on that point.

**Comment by sogaiu** [comment]
> What functions do is more relevant than what they're called.

I agree [1].

Perhaps we're better off starting with not-so-nice names and only once the functions / callables have proven their worth, good names / aliases can be assigned :P

---

[1] On a tangential topic of naming, IMO, the continued use of very misleading names can have cumulative undesirable effects (like "oxidation" and "reduction" in chemistry).

**Comment by CosmicToast** [comment]
> What functions do is more relevant than what they're called.

I actually disagree, these are equally important.
A function that is poorly named is a function that doesn't exist.

We, very often, have users coming in, asking for stuff (sometimes even proposing VM changes), only to have their use-case instantly solved by a function existing, and them having no idea it existed.
It isn't feasible to read *and* retain the entirety of the standard library documentation and definitions (and examples, since those are often necessary to really understand what the function does).
As such, function *names* are how people actually realize that what they're trying to do is an option.
Function names are the very first line of documentation, and documentation is a cornerstone of any API, let alone a PL.

Having consistent behaviors, semantics, and having all of those align with the naming scheme has additional benefits beyond this.
Let's say we have ruby-style `foo` and `foo!` with the latter being in-place, and only accepting mutable data structures for the latter.

Imagine, for instance, we add an immutable variant of `put`, and call it `assoc`, to comply with historical naming.
The user would need to know this history, or to have read and grasped the meaning of the `assoc` documentation and examples to use it, rather than doing something like `|(freeze (put (thaw $) $1 $2))`.
In the meanwhile, if we have the above naming scheme, and instead these are named `put!` and `put`, the user can instantly infer the above.
It also increases documentation locality - they will appear next to one another in automatically generated docs (which otherwise *need* to be supplemented by handwritten docs[^1].

[^1]: I may consider making these for Janet 2 regardless. Hopefully, my prior work (e.g in the [alpine user handbook](http://docs.alpinelinux.org)) qualifies me.

**Comment by primo-ppcg** [comment]
> Very often, users will come in, ask for stuff (sometimes even propose VM changes), only to have their use-case instantly solved by a function they've never heard of.

I think that's a valid point. My [very first issue](https://github.com/janet-lang/janet/issues/1117) was requesting the behavior of `or` to be changed to match that of `any?`. It's not that I hadn't seen it, but I had assumed the trailing question mark meant it would always return a boolean. Perhaps a discussion or wiki could be opened regarding proposed breaking changes, that could later be formalized.

**Comment by sogaiu** [comment]
Looks like there is now a [related discussion item](https://github.com/janet-lang/janet/discussions/1251).

---

Interesting that although the discussion item mentioned this issue, the discussion item doesn't automatically get shown here (like issues or prs seem to).

**Comment by bakpakin** [comment]
I think it is a possible change - it may be worth returning a string if the input to the function is `(bytes? x)`. But  a buffer would actually be more consistent - the return value is mutable in the case of arrays and tuples.

Another strange behavior as a result of the reverse implementation is calling reverse on dictionaries. This doesn't error but does result in strange arrays full of holes in many cases:

```janet
repl:1:> (reverse {1 2 3 4 5 6})
@[nil 2 nil]
```

**Comment by primo-ppcg** [comment]
> Another strange behavior as a result of the reverse implementation is calling reverse on dictionaries.

I went back to confirm that the behavior was present in 1.29.1 and 1.30.0 :sweat_smile: 
I agree that if no error is produced, that it should at least do something reasonable.
