### ISSUE TITLE
Will janet be a compiler beyond the VM

### ISSUE THREAD

**Issue by EinKindAndy** [janet-lang/janet#130]
Will janet be both an interpreter and a compiler that generates the executable directly?

**Comment by bakpakin** [comment]
Depends what you mean.

You can create bytecode images which can be loaded via the janet executable. These can be imported much like normal .janet source files. These images can be generated to include an entire application, so work as a form of distribution that is not source form.

If you mean native compilation, not in the short term, no. From an external point of view, however,  packaging a simple interpreter with a bytecode image isn't vastly different compared to native compilation in a language that requires (or is often combined with) a runtime library (Go, Rust, D, even C). Since the compiled interpreter and core library is anywhere from 250kb to 500kb depending on options (seems to usually be about 450 - 500kb on x64 linux), the space overhead is negligible in most cases. The main difference is performance, although this doesn't have to be as large as one might guess.

The strategy for deploying self contained binaries for Janet would be statically linking libjanet.a with a bytecode image and a bit of boilerplate C code (or something similar). This is not yet automated but could be done manually with some work (write the boilerplate C, generate an image with `(make-image)`, compile, link, profit). Making this easy and automatic is on my current road map. (version 1.1?).

All that said, there isn't much fundamentally different between compiling Janet to machine code and common lisp to machine code (except a compiler for the latter actually exists). A lot of work would be required to write a native compiler Janet, and a LOT of work would be needed to make the performance gains worth while.

**Comment by EinKindAndy** [comment]
Thanks for the complete reply. I just expect a native compilation including statical dependency or a similar tool to package them. In the end, Janet is fascinating, thanks.
