### ISSUE TITLE
if-let macro behavior changed?

### ISSUE THREAD

**Issue by 5thWall** [janet-lang/janet#1319]
Hello, I recently picked up Janet and I came across [this usage in junk-drawer](https://github.com/AlecTroemel/junk-drawer/blob/8ea84fa60929b0bc7281bc46c9b52c01a6e4265b/junk-drawer/tweens.janet#L179-L182) which is currently throwing a compile error on `1.32.1` with: `compile error: unknown symbol new-elapsed`.

```janet
(if-let [new-elapsed (+ elapsed 1)
            complete? (> new-elapsed duration)]
  (remove-entity wld tween-ent)
  (put tween-data :elapsed-time new-elapsed))))
```

There's nothing in the documentation about this, so I'm wondering if this is the intended behavior?

**Comment by sogaiu** [comment]
Possibly related https://github.com/janet-lang/janet/issues/1189

Also, may be you meant `1.32.1` and not `3.32.1`?

**Comment by bakpakin** [comment]
So I have bisected this change to Janet version 1.27.0, but I think the new behavior is the correct behavior. The bindings inside if-let are short-circuiting, meaning that in the false case, it is possible that some of the bindings do not have values at all. While we could initialize things to nil, that doesn't sit right with me.

The above code makes sense since new-elapsed will always be truthy, but really should be written:

```janet
(let [new-elapsed (+ elapsed 1)]
  (if (> new-elapsed duration)
    (remove-entity wld tween-ent)
    (put tween-data :elapsed-time new-elapsed)))
```

**Comment by AlecTroemel** [comment]
Ya letting the false branch of the `if-let` use variables defined could definitely lead to some confusing code :laughing:, since you don't necessarily know which definition in the let was false. 

Hopefully I did depend on the old behavior anywhere else, otherwise I'll be kicking myself
