### ISSUE TITLE
Some advice to write high quality code in Janet?

### ISSUE THREAD

**Issue by EinKindAndy** [janet-lang/janet#136]
As a beginer of Janet,  I try to write some toy code , so I add a test imitating kostya's benchmarks (https://github.com/kostya/benchmarks).  Also, I implement a Pony version that not exists in the benchmarks as an exercise. I hope the implementation has higher performance.

Janet:
time janet brainfuck2.janet 
ZYXWVUTSRQPONMLKJIHGFEDCBA

real	3m16.466s
user	3m16.460s
sys	0m0.000s

Pony:
time ./bf_pony bench.b 
ZYXWVUTSRQPONMLKJIHGFEDCBA

real	0m2.582s
user	0m2.680s
sys	0m0.024s

Janet's implementation:

``
(def INC 0)
(def MOVE 1)
(def PRINT 2)
(def LOOP 3)
(def *content* @"")

(defn tape-builder []
  (var pos 0)
  (def data @[0])
  (let [
        getv (fn [] (data pos))
        inc (fn [x] (set (data pos) (+= (data pos) x)))
        move (fn [x] 
               (set pos (+= pos x))
               (while (>= pos (length data))
                 (array/push data 0)))]
    {:getv getv :inc inc :move move}))

(defn brainfuck [text]
  (defn parse [source _i ops]
    (var i _i)
    (while (< i (length source))
      (do
        (def c (source i))
        (cond 
          (= c 43) (array/push ops {:operator INC :value 1})
          (= c 45) (array/push ops {:operator INC :value -1})
          (= c 62) (array/push ops {:operator MOVE :value 1})
          (= c 60) (array/push ops {:operator MOVE :value -1})
          (= c 46) (array/push ops {:operator PRINT})
          (= c 91) (do
                     (def new_ops @[])
                     (def new_i (parse source (+ i 1) new_ops))
                     (set i new_i)
                     (array/push ops {:operator LOOP :value new_ops}))
          (= c 93) (break i))
        (+= i 1)
        ))
    i)
  (defn _run [ops tape]
    (each op ops
      (do 
        (def operator (op :operator))
        (cond 
          (= operator INC) ((tape :inc) (op :value))
          (= operator MOVE) ((tape :move) (op :value))
          (= operator LOOP) (while (> ((tape :getv)) 0) (_run (op :value) tape))
          (= operator PRINT) (buffer/push-byte *content* ((tape :getv)))
          ))))
  (defn run []
    (def lst @[])
    (parse text 0 lst)
    (_run lst (tape-builder)))
  (run))

#(def text (file/read (file/open path) :all))
(def text
">++[<+++++++++++++>-]<[[>+>+<<-]>[<+>-]++++++++
[>++++++++<-]>.[-]<<>++++++++++[>++++++++++[>++
++++++++[>++++++++++[>++++++++++[>++++++++++[>+
+++++++++[-]<-]<-]<-]<-]<-]<-]<-]++++++++++.")

(brainfuck text)
(print *content*)

**Comment by bakpakin** [comment]
I'd be glad to help, as this is great example on writing cleaner and more efficient janet code.
I'm not sure if this would be allowed on the bencmark, but using Janet's PEG engine it is very easy to compile brainfuck into something else. Also, rather than writing our own interpreter we can use Janet's instead. With these two ideas, we get some code that should be much more efficient (although still not really competitive with native code like Pony or C).

```clojure
#
# Compiling brainfuck to Janet.
#

(def bf-peg
  "Peg for compiling brainfuck into a janet source ast."
  ~{:+ (/ '(some "+") ,(fn [x] ~(+= (DATA POS) ,(length x))))
    :- (/ '(some "-") ,(fn [x] ~(-= (DATA POS) ,(length x))))
    :> (/ '(some ">") ,(fn [x] ~(+= POS ,(length x))))
    :< (/ '(some "<") ,(fn [x] ~(-= POS ,(length x))))
    :. (* "." (constant (buffer/push-byte CONTENT (get DATA POS))))
    :loop (/ (* "[" :main "]") ,(fn [& captures]
                                  ~(while (> (get DATA POS) 0)
                                     ,;captures)))
    :main (any (+ (set " \t") :loop :+ :- :> :< :.)) })

(defn brainfuck
  "Run brainfuck."
  [text]
  (eval
    ~(let [DATA (seq [_ :range [0 1024]] 0)
           CONTENT @""]
       (var POS 0)
       ,;(peg/match bf-peg text)
       CONTENT)))

(def text
">++[<+++++++++++++>-]<[[>+>+<<-]>[<+>-]++++++++
[>++++++++<-]>.[-]<<>++++++++++[>++++++++++[>++
++++++++[>++++++++++[>++++++++++[>++++++++++[>+
+++++++++[-]<-]<-]<-]<-]<-]<-]<-]++++++++++.")

(:write stdout (brainfuck text))
```

On my laptop, I get the following time:

```
calvin@calvin-p51:~/code/jbf$ time janet bench.janet
ZYXWVUTSRQPONMLKJIHGFEDCBA

real	0m10.787s
user	0m10.776s
sys	0m0.004s
```

Definitely an improvement.

---

As for improving your code rather than rewriting it, here are a few tips for improving code speed. Take these with a grain of salt, as you often don't need to optimize prematurely!

- Janet's OO functionality is slower than in a native Object Oriented language. It is there for flexibility, and is mostly appropriate for high level operations and polymorphism. Don't use it an expect it to be fast.

- In general, don't try to add too much abstraction around things if you care about performance. Keep your hot inner loops low level if you want them fast, and don't go adding extra layers of functional indirection unless you need it. Janet's compiler is pretty dumb and Janet itself is not optimized for speed. Janet is probably similar to Python/Lua/Perl/Ruby for speed right now.

**Comment by EinKindAndy** [comment]
Thank you so much. It's a great pleasure to gain the new points. Thanks for the helpful advice to learn more about Janet.
