### ISSUE TITLE
Document `&keys` better.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet#1361]
Until recently, I didn't recognize the example for `&keys` on https://janet-lang.org/docs/functions.html was using destructuring. I thought destructuring was a mandatory syntax for `&keys`.

However, I realized that `&keys` doesn't require destructuring.

https://janet-lang.org/docs/functions.html should point out that destructuring after `&keys` is optional.

**Comment by sogaiu** [comment]
By "the example for &keys", are you referring to something in [this section](https://janet-lang.org/docs/functions.html#Keyword-style-arguments)?

I don't quite follow what you're getting at, though possibly it's better to file an issue at the [website repository](https://github.com/janet-lang/janet-lang.org) rather than here.

If you do decide to file an issue there, may be you wouldn't mind elaborating a bit more on the specifics of what you mean.

**Comment by amano-kenji** [comment]
Okay.

**Comment by amano-kenji** [comment]
https://github.com/janet-lang/janet-lang.org/issues/205

**Comment by sogaiu** [comment]
Thanks!
