### ISSUE TITLE
(doc cond) bug

### ISSUE THREAD

**Issue by michal037** [janet-lang/janet#141]
The documentation is badly printed. The order of words is bad.
I am using `janet-v1.1.0-windows.zip` on Windows 10.

https://github.com/janet-lang/janet/blob/6887dd05f674ccf931bc99dabeca4fc095988a08/src/boot/boot.janet#L157

![bug](https://user-images.githubusercontent.com/7441419/60943472-6d36da80-a2e6-11e9-8610-24f42b993aec.png)

---

What is it for (5381: 5908)?

**Comment by bakpakin** [comment]
The pair `(5381: 5908)` is the (byte start index, byte end index) pair in the file. Rather than line, col, this is unambiguous and gives a range rather than a point, usually the entire s expression. Using vim, you can type `:5381go` to go to a specific byte (character). Emacs has something similar.

I will look at the strange formatting issue, however.

**Comment by bakpakin** [comment]
The culprit was windows text mode when reading files, which was inserting a carriage return into the parsed doc strings. The docstring formatter did not like that and was screwing it up. My making the parser ignore carriage returns in double quoted strings, we solve the problem. We also try to make most file utility functions use binary mode when possible. It's now fixed on the latest master.
