### ISSUE TITLE
Would Janet consider GPL over MIT?

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#144]
Is there a strong preference on license at the moment?  Or is MIT more chosen as a "don't care" license?

I see the library for web (Circlet) is GPL https://github.com/janet-lang/circlet due to integration with Mongoose.

GPL is a more-free language than MIT, and I think it would put Janet in the same/similar space as GNU Guile (other than not being a GNU project), but with a much more modern syntax / conventions.

**Comment by bakpakin** [comment]
I prefer MIT in general simply because I don’t mind if people want to use Janet for proprietary uses and don’t want to open source their code.

I would consider dual licensing future Janet commits under GPL as well if there is a desire for that, so that derivative software can be GPL without any possibility of being incompatible. I believe MIT should be very compatible with GPL software, but a dual license would be more explicit.

I probably will not make Janet only licensed under GPL.

**Comment by ahungry** [comment]
Makes sense, thanks - FWIW, I think you're correct - any MIT project can just be forked and relicensed as GPL if the forker chose so (at least, all the future contributions that are tagged on top).

I think a dual license would be neat.
