### ISSUE TITLE
Possible retagging of v1.35.2

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#1483]
I’m trying to fix the Homebrew formula for Janet. As part of a PR connected with that (Homebrew/homebrew-core#180051), I was asked to confirm whether v1.35.2 had been retagged as Homebrew has a SHA256 value in its formula for v1.35.2 that is different to what you get if you download the file now. Was a commit retagged?

**Comment by sogaiu** [comment]
For reference, the current sha256 I get for `janet-1.35.2.tag.gz` is:

```
$ sha256sum janet-1.35.2.tar.gz 
947dfdab6c1417c7c43efef2ecb7a92a3c339ce2135233fe88323740e6e7fab1  janet-1.35.2.tar.gz
```

The two values in at https://github.com/Homebrew/homebrew-core/pull/180051 are:

* a0e8d56c6025988c8432353e7d67f2c2eb66404d233e6e8113430085dcb4f754
* 947dfdab6c1417c7c43efef2ecb7a92a3c339ce2135233fe88323740e6e7fab1

**Comment by bakpakin** [comment]
I did Retag 1.35.2 due to release mistake.

**Comment by carlocab** [comment]
It might help to read the [Git docs](https://www.git-scm.com/docs/git-tag/2.46.0#_on_re_tagging) on retagging, as it has some very strong words about doing this.

I understand the temptation to re-tag, but this isn't very nice to your downstream consumers, and also has some security implications.

**Comment by sogaiu** [comment]
While the points made in the git docs are not bad, I believe it is up to individuals to make their own decisions.

I think you assume that someone was ignorant of the matter and worded accordingly.  Did it occur to you that someone might have known and went ahead with re-tagging anyway?

Your wording came across as arrogant to me and I think you'd have more constructive effects if you reconsidered your wording for future communications of these sorts.

Peace.

**Comment by sogaiu** [comment]
> Ok, how should I have worded it instead?

Instead of starting off with:

> It might help to read the [Git docs](https://www.git-scm.com/docs/git-tag/2.46.0#_on_re_tagging) on retagging, as it has some very strong words about doing this.

you might have just stated initially your concerns about retagging and its potential impact on Homebrew and its users.  I think leading with a paragraph such as the above can easily come across as chastisement.  Why begin that way?  Do you really think people will be receptive to that kind of opening?

You might have also mentioned the document later in your comment and said something to the effect of, "perhaps you know already about possible implications of retagging, but FWIW, here is a document that spells things out in detail in ways that concern us".

> Yes, it did. However, I am not a mind-reader, so I can't know for sure.

Regarding being a mind-reader, I'm not either, but I can ask questions before assuming things (I admit I don't always do this, but I try).  It doesn't have to happen in all one message AFAIU.

**Comment by carlocab** [comment]
> can easily come across as chastisement

Perhaps, but it seems to me that taking it as chastisement is more likely to be an assumption, rather than something grounded in fact. This seems a lot like an assumption too:

> I think you assume that someone was ignorant of the matter and worded accordingly.

So I'll advise you to take your own advice:

> I can ask questions before assuming things

If you don't want me to assume things about your knowledge and intent, please don't assume things about mine either.

**Comment by sogaiu** [comment]
Sounds good to me.

**Comment by bakpakin** [comment]
I do try to tagging issues, however the real issue seems to be that release SHAs don't match what homebrew expected (which was probably caused by a retagging). 

We should probably start including release SHAs off all artifacts during build to check things better. I would be curious to double check the old and new tarballs to see what the difference is.

**Comment by sogaiu** [comment]
For any interested parties, I found that the commit that the tag v1.35.2 referred to was different on my machine than what is currently visible here:

local: 94b7a69741e3e0acca962c26180acb0e47681911
github: fda0a081f59c03d851658bf8f6d12371631f08f1

May be it's possible to rebuild tarballs and examine the resulting checksums?

**Comment by sogaiu** [comment]
[janet-1.35.2-94b7a69.tar.gz](https://github.com/user-attachments/files/16576575/janet-1.35.2-94b7a69.tar.gz) is a tarball based on 94b7a69741e3e0acca962c26180acb0e47681911.

I get what appears to match the older checksum for it:

```
$ sha256sum janet-1.35.2-94b7a69.tar.gz 
a0e8d56c6025988c8432353e7d67f2c2eb66404d233e6e8113430085dcb4f754  janet-1.35.2-94b7a69.tar.gz
```

For comparison, [janet-1.35.2-fda0a08.tar.gz](https://github.com/user-attachments/files/16576580/janet-1.35.2-fda0a08.tar.gz) is the newer tarball based on 
fda0a081f59c03d851658bf8f6d12371631f08f1, and the checksum I get for it is:

```
$ sha256sum janet-1.35.2-fda0a08.tar.gz 
947dfdab6c1417c7c43efef2ecb7a92a3c339ce2135233fe88323740e6e7fab1  janet-1.35.2-fda0a08.tar.gz
```

These checksums match what are reported for the old and new tarballs as noted in [this comment](https://github.com/janet-lang/janet/issues/1483#issuecomment-2269005339).
