### ISSUE TITLE
Changing the files used by the `bundle/` functions

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#1486]
If it's not too late, I'd like to suggest that the `bundle/` functions not rely on files in the `bundle/` directory. My reasoning:

1. The information in these files is useful for consumers of modules and putting it in a subdirectory makes it more difficult to find.

2. A practical consequence of how the private [`get-bundle-module`](https://github.com/janet-lang/janet/blob/2dcc0adc0ee45e53cf480e6c0e294e0fea53629c/src/boot/boot.janet#L4092-L4111) and public [`bundle/install`](https://github.com/janet-lang/janet/blob/2dcc0adc0ee45e53cf480e6c0e294e0fea53629c/src/boot/boot.janet#L4214-L4273) functions work means that module authors are likely to have a `info.jdn` and `init.janet` files in the `bundle/` directory. In other words, you have two files that both have filenames that begin with `in` which I'm finding visually confusing.

Instead, my suggestion is that the `bundle/` directory be removed and `info.jdn` file (for project metadata) and `bundle.janet` file (for use by the bundling code) be stored in the project root.

**Comment by bakpakin** [comment]
The semantics of the `bundle/` directory are pretty simple - the whole directory is copied to `:syspath/bundle/:bundle-name/` on install.

A single `bundle.janet` file would work well until a build process gets more complicated such that you want to split things into multiple files. No problem, let's just `(import ./my-compiler-wrapper)` and any other module we need to build, test, lint, etc our project. If these are from other external bundles and on the syspath, you are fine. However relative imports might break. The idea of using the `bundle/` directory is that any scripting you put in there will work fine after it is installed since locally directory structure is preserved.

All that said, I guess I would be ok with adding some way to alias `bundle.janet` and `info.jdn` in the project root to the current respective files in the simple case. I just want to be clear on why this slightly clunky interface is used here.

**Comment by pyrmont** [comment]
> The idea of using the `bundle/` directory is that any scripting you put in there will work fine after it is installed since locally directory structure is preserved.

I'm a bit confused by this. What scripting would you have there that would work after installation? Once a bundle is installed, shouldn't any files that are necessary for the functioning of the bundle be in the equivalent of `declare-source`?

**Comment by bakpakin** [comment]
Mostly uninstall, but you could have some kind of health check, system configuration, driver updates, etc. However, these are things you also want to be able to run unmodified _before_ installing a bundle. With JPM, one minor annoyance for testing was that for truly faithful testing, you need to install a package and only then run tests. You can work around this with various shims/hacks but it should be easier IMO. i.e. - `jpm deps` -> `jpm install` -> `jpm test`.

**Comment by pyrmont** [comment]
Got it. In that case, count me down as someone appreciating the `bundle.janet`/`info.jdn` alias approach :)
