### ISSUE TITLE
Potential memory leak with slurp

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#150]
I'm working on a profiling module that will report memory taken by a form, by looking at the before/after of the RSS within the process.  I notice when I do a memory intensive form operation (such as slurping a 40MB file) the RSS of the REPL process continually increases, even if nothing refers to the evaluation result of slurping the file.

At what point would the GC or a manual process be able to reclaim the memory?

```
janet:676:> (b/time (fn [] (slurp "/home/mcarter/woot.gif")))
RSS: 745619456 (711.08 MB)
Form memory usage: 42172416 (40.22 MB)
CPU Time taken: 0.032036 (sec)
```

That's after running slurp in a loop for some number of iterations (I guess I could put together a more concrete sample of vanilla janet without my bench module to confirm it is indeed just a problem with slurping in a loop).

**Comment by ahungry** [comment]
Ok, given this test:

```
dd if=/dev/zero of=/app bs=512 count=102400
janet
(map (fn [x] (slurp "/app/dummy.img") x) (range 10))
```
When run in a docker, I see in docker stats that the memory of janet process goes up to ~505MB and never goes back down.

Is there a way to free memory from slurp?

**Comment by bakpakin** [comment]
Interesting. I very much doubt that there is a true memory leak, but you can run `valgrind janet` on the process to see if there is a leak at the C level. The example above runs valgrind clean on my machine.

It seems to be that the GC is just not running at all! Manually calling `(gccollect)` after many large reads that should be collected does the trick. The culprit is simply the way that the GC works. We tried to track how much memory we have allocated since the last collection, and once that exceeds a threshold value, we reset and run a collection. However, some kinds of memory are not counted in this threshold value - like the contents of a buffer object (a buffer value has two parts - a fixed header part and a variable-sized contents part). Counting the size of the contents of a buffer towards this threshold should help the GC run in all cases.

**Comment by bakpakin** [comment]
Try the latest master, this instance should be fixed, along with some other possible cases. In all cases, running `(gccollect)` should collect the memory.

**Comment by ahungry** [comment]
The profiler check in my bench module now shows RSS drop after the loop is done, so much better, thanks!

You're right on docker stats - I think that's just a docker thing (if I do the same simulation over and over, the docker RSS just keeps growing, so it seems docker itself is not reclaiming ram a container reserved or something).
