### ISSUE TITLE
assoc macro...

### ISSUE THREAD

**Issue by eko234** [janet-lang/janet#1501]
Hi, I've been rediscovering Janet lately and I want to know if you would consider checking a pr that implements assoc with a macro, I know maps and arrays are faster, but we could provide a macro for use cases in which users don't care about speed but ergonomics of manipulating immutable data structures. Ty!

**Comment by sogaiu** [comment]
Possibly of interest is [this comment](https://github.com/janet-lang/janet/issues/1248#issuecomment-1674938254) from @CosmicToast:

> Imagine, for instance, an immutable variant of put is added and called assoc, to comply with historical naming.

**Comment by eko234** [comment]
Interesting take, I like the bang idea, but I guess it might break some things
> Possibly of interest is [this comment](https://github.com/janet-lang/janet/issues/1248#issuecomment-1674938254) from @CosmicToast:
> 
> > Imagine, for instance, an immutable variant of put is added and called assoc, to comply with historical naming.

**Comment by pepe** [comment]
These are my two cents, but I have been doing that lately with `(struct :key value ;(kvs old-struct))`.

TBH, I am against most of the additions to the standard library, especially those for convenience.

**Comment by sogaiu** [comment]
I wonder whether trying to add things to spork first and if something seems useful enough, it gets considered for addition to janet itself could be a path worth considering in general.

This way things get can get tried out and modified in a "less high stakes" (?) environment.

**Comment by CFiggers** [comment]
Before you do that, I want to draw your attention to the `struct/with-proto` function.

Janet has the concept of [Prototypes](https://janet-lang.org/docs/prototypes.html), which is where a table or struct will go looking in its "parent" table (or rather, "prototype") for a key if it doesn't have that key itself. Janet uses this to do a very simple, but surprisingly capable version of OOP using data structures instead of Classes.

Structs can have prototypes—this is actually really similar to the way Clojure does Persistent Data Structures (except that Clojure hides all that under the hood).

The `struct/with-proto` function has very similar semantics and usage to Clojure's `assoc`.

In Clojure you might do something like this:

```clojure
user=> (def m {:a 1 :b 2})
#'user/m
user=> (def n (assoc m :c 3))
#'user/n
user=> n
{:a 1, :b 2, :c 3}
user=> (def o (assoc m :a 6))
#'user/o
user=> o
{:a 6, :b 2}
user-> m
{:a 1, :b 2} ; Original struct is unchanged
```

You can do almost this exact thing with `struct/with-proto` in Janet:

```janet
Janet 1.36.0-dev-c82fd106 linux/x64/gcc - '(doc)' for help
repl:1:> (def m {:a 1 :b 2})
{:a 1 :b 2}
repl:2:> (def n (struct/with-proto m :c 3))
{:c 3}
repl:3:> (struct/proto-flatten n)
{:a 1 :b 2 :c 3}
repl:4:> (def o (struct/with-proto m :a 6))
{:a 6}
repl:5:> (struct/proto-flatten o)
{:a 6 :b 2}
repl:6:> m
{:a 1 :b 2} # Original struct is unchanged
```

The only "gotcha" to be aware of is that when you make a struct with a prototype it APPEARS to lack the keys that are only found in the prototype when you do things like `(print)`. But the keys are in fact there, and you can still access them the usual way (either using `get` or like `(o :b)`). When a key isn't found in the struct itself, Janet "falls back" to the prototype struct. And if that prototype has a prototype, it'll "fall back" again, as many times as there are prototypes. You can see what all keys are there "for real" using `struct/proto-flatten` as you see me doing in the example above.

As for the ergonomics—`struct/proto-flatten` is less pleasant to type than `assoc`—you can even fix that by just putting somewhere at the top of your file:

```janet
(def assoc struct/with-proto)
```

And then write your Clojure-ish code as you normally would.

**Comment by sogaiu** [comment]
@CFiggers Nice -- TIL :)

---

@eko234 Possibly of interest might be [this spork issue](https://github.com/janet-lang/spork/issues/108).
