### ISSUE TITLE
fn shorthand macro

### ISSUE THREAD

**Issue by curist** [janet-lang/janet#152]
Is it feasible to include something likes clojure's function shorthand?
I did an implementation using macro, would love to see it to be included in Janet core.
```clojure
(defmacro $
  `fn shorthand
  usage:
  ($ +) skipping param placeholder, param is append to last position
  ($ + _) exactly the same as above example
  ($ string _1 _2) accepting multiple args`
  [& args]

  (def placeholders
    (->> args
         (map (fn [ind sym] {:ind ind :sym sym}) (range (length args)))
         (filter (fn [p] (= (type (p :sym)) :symbol)))
         (filter (fn [p] (string/has-prefix? '_ (p :sym))))
         (map (fn [p] {:ind (p :ind)
                       :sym (p :sym)
                       :p-ind (or (scan-number (string/slice (p :sym) 1)) 1)}))))

  (def uniq-placeholder-keys
    (keys (reduce (fn [t p] (put t (p :p-ind) true)) @{} placeholders)))

  (def uniq-placeholder-len (length uniq-placeholder-keys))

  # args checking
  (cond
    (>= uniq-placeholder-len 2)
    (when (deep-not= (sort uniq-placeholder-keys)
                     (range 1 (+ 1 uniq-placeholder-len)))
      (error "placeholder indexes are not in sequential order"))
    # special check for len = 1
    (and (= uniq-placeholder-len 1)
         (not (all (fn [p] (= '_ (p :sym))) placeholders)))
    (error "use _ as placeholder if there is only one placeholder"))

  (def body (array ;args))

  (each p placeholders (put body (p :ind) (symbol 'a (p :p-ind))))

  (def fn-args (map (fn [i] (symbol 'a i)) (range 1 (+ 1 uniq-placeholder-len))))

  (case uniq-placeholder-len
    0 ~(fn [arg] (,;body arg))
    ~(fn [,;fn-args] (,;body))))


(print (($ string 'a) 'b))
(print (($ string 'a _) 'b))
(print (($ string _ 'a) 'b))
(print (($ string _2 _1 'a) 'b 'c))
(print (($ string 'a _1 _2) 'b 'c))
(print (($ string 'a _3 _4 _5 _6 _7 _1 _2) 'b 'c ;(range 5)))

(pp (map ($ * 3) (range 10)))
(pp (map ($ / _ 10) (range 10)))
(pp (map ($ * _1 _2) (range 1 11) (range 21 31)))

(pp (($ _ 'Hello " " 'world '!) string))

(pp (($ * _ _) 2))
(pp (($ string _2 _1 _2) 'a 'b))
(pp (($ string 'a _ 'b _) 'c))

```

**Comment by curist** [comment]
Would be even better if we can make it a reader macro, which will cut off one extra space.

```
$(% _ 10)
($ % _ 10)
```

**Comment by bakpakin** [comment]
Thanks, I think such a macro would be pretty useful in the core! If we do make it a "reader macro" though, a better signature would be something like

```
($fn (+ _1 _2))
```
Which could possibly look like the following in reader macro form:

```
$(+ _1 _2)
```
This is in line with how other macros works, and also lets us do things like:

```
${:a _1 :b _2}
```

Which would expand to 

```
($fn {:a _1 :b _2})
```

I would like to add this in the core with a reader macro, but this requires excluding certain characters from symbols (such as the dollar sign) with the way reader macros are now.

**Comment by bakpakin** [comment]
So I took your code an ran with it, and added a more robust version to the core library. It should have fewer limitations, and is a bit different than the version presented above. Updated in 44e752d7375258147f5341837f5be9d09171641c.

Example:

```clojure
(map |(string/split "," $) ["1,2,3,4" "5,6,7,8" "9,10,11,12"])
;#-> @[@["1" "2" "3" "4"] @["5" "6" "7" "8"] @["9" "10" "11" "12"]]
```

Differences:
- Usage is `(short-fn (+ $0 $1))`. Using the `|` reader macro (new), this becomes `|(+ $0 $1)`. Notice that the macro is no longer variadic.
- There is also no more limitation with nesting, you can do `|(+ $ $2 $4 (* $3 $5))`, `||$`, `|{:a $ :b (+ $2 $3)}
- Use of underscore is replaced with `$` so there is no possible issues with `gensym` which also generates underscore prefix symbols (some of which may look like valid numbers).
- Variadic short functions are supported. `(|(length $&) 1 2 3 4 5)` evaluates to 5.
- The function body can be any form, not just a tuple. For example, a function that returns a constant is just `|:constant`.

I used the pipe character for the reader macro because it was the character that seemed to have the least possible impact on existing code. The biggest problem with the reader macros right now is they require reserved characters to work. This keeps the grammar and parser simple, but does quickly exhaust characters. On the other hand, having few reader macros is probably a good thing.

**Comment by curist** [comment]
so good! I have to take a thorough look at your implementation later. I figured the initial implementation didn't take care of things like `:table`, `:tuple` etc, and probably need to do some recursive parsing on it. So happy to see that you went ahead and cover that use case in the implementation :smile:

**Comment by bakpakin** [comment]
Yeah, all of the gross stuff was already in the macex1 macro (which needed to be slightly modified). This saves a lot of duplication.
