### ISSUE TITLE
jpm build stack overflow

### ISSUE THREAD

**Issue by curist** [janet-lang/janet#158]
```sh
error: stack overflow
  in create-buffer-c-impl [/usr/local/lib/janet/cook.janet] at (9285:9579)
  in <anonymous> [/usr/local/lib/janet/cook.janet] at (12368:12429)
  in do-rule [/usr/local/lib/janet/cook.janet] at (2403:2409)
  in do-rule [/usr/local/lib/janet/cook.janet] (tailcall) at (2317:2329)
```
it happens when trying to `jpm build` with around 8100 chunks.

**Comment by curist** [comment]
narrowed down to
```clojure
(string ;(interpose "" (buffer/new-filled 8188)))
```

**Comment by bakpakin** [comment]
Oops, this is pretty easy to fix. Simple use `(string/join (interpose "" chunks))` instead, which does not overflow the stack.

**Comment by curist** [comment]
Although now `jpm build` runs fine, it still leave the potential `splice` overflow untouched right? Not saying I will do splice large array everyday, but an abstraction with certain limit like this is a mind burden, personally I would like to see the `splice` overflow thing get tackled. And, obviously, I have no idea how much work would that take...

**Comment by bakpakin** [comment]
It's pretty easy. Each fiber sets a maximum amount of stack that they can take, which defaults to JANET_STACK_MAX. This is the default and is set in janet.h (or janetconf.h). We can simply increase the default value to 0x7fffffff, which would solve the problem. It is set low to start so an accidental infinite recursion will error quickly rather than slowly, but other than that I don't know if there is much reason to limit it.

It can also be set at runtime via `(fiber/setmaxstack fiber int)` and read via `(fiber/maxstack fiber)`

**Comment by curist** [comment]
I'm just thinking at a distant look, `(apply + (range 17000))` is the same as `(+ ;(range 17000))`, while the former works and the later doesn't, and I'm not sure why there is such difference as language user.

**Comment by curist** [comment]
And I'm not arguing this is a must fix, but having the consistency over the language give me nice feelings. After all, Janet is love, Janet is life. ❤️

**Comment by bakpakin** [comment]
Actually, `apply` shouldn't work either. That it works is a bug :). There is a missing stack overflow check in the JOP_TAILCALL instruction.

**Comment by bakpakin** [comment]
I think I will bump up the default fiber max stack size to INT32_MAX. I find myself using splicing a lot, and it can help in those cases. However, in general splicing requires copying everything to the stack so it should be used carefully.
