### ISSUE TITLE
`put-in` complains about not expected type

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#162]
Repro:

```
(def h @{:a {:b {:c 2}}})
(put-in h [:a :b :c] 3)

error: expected array|table|buffer, got <struct 0x560752256DB0>
  in put-in [boot.janet] at (30828:30845)
  in _thunk [repl] (tailcall) at (195:217)
```

But for

```
(def h @{:a @{:b @{:c 2}}})
(put-in h [:a :b :c] 3)

@{:a @{:b @{:c 3}}}
```

I can see in the code that you are using `set` in update-in, so you are expecting `table` or `array` only. 

I am not saying that this is bug per se, but the behaviour was surprising to me.

**Comment by pepe** [comment]
Maybe we could have `update-in` for all types returning new changed structure, and `update-in!` for mutable types which will modify an original structure. This approach is common in Clojure, which is only Lisp dialect I know :-).

**Comment by pepe** [comment]
`update-in` has the same behaviour as `put-in`.

**Comment by pepe** [comment]
So the same could be said for `update`, so `put-in` and `update-in` is consistent with the old API.

So the problem was my expectations. Feel free to close this.

**Comment by bakpakin** [comment]
Janet idata structures have different, more traditional characteristic than those of Clojure, and we don't add the ! suffix to functions that mutate things because so many functions do it. Also, structs are flat, immutable hashtables - this means that updating one involves copying the whole thing, which is slow and I want to avoid because often it is not needed. For nested structs, this means copying at each level. Lastly, it seems weird to me to try and detect the innermost table and mutate that.

As you say, the current behavior of update-in matches other mutating functions in the core.
