### ISSUE TITLE
Shorthand array access

### ISSUE THREAD

**Issue by honix** [janet-lang/janet#17]
I like those container:key shorthand for structs and tables. (This is not documented feature as I see)
```clojure
(def x @{:key 'value})
x:key => value

(set x:anotherkey 'anothervalue)
x => @{:key value :anotherkey anothervalue}
```
But why it is doesn't works with tuples and arrays?
```clojure
(def x @[1 2 3])
x:0 => error in repl: expected integer key for data structure

(set x:0 -1) => error in repl: expected integer key for data structure
```

**Comment by honix** [comment]
Can you please explain dot operator (?) here:
https://github.com/janet-lang/janet/blob/master/examples/life.janet#L19
And here:
https://github.com/janet-lang/janet/blob/master/examples/life.janet#L27

**Comment by bakpakin** [comment]
The dot operator is like an array indexing operator. An expression `a.b` is treated by the compiler much like `(get a b)`. The colon operator works with keywords. An expression `a:b` is treated by the compiler like `(get a :b)`.

In some older version of janet, the dot operator was able to index with integer keys. In other words, you could do `a.0` to get the first element of a tuple. I have removed that for now because I did not want to commit to the syntax, but I think it might be useful.

**Comment by bakpakin** [comment]
The old behavior was removed as I was making some large changes to Janet internals about representation of integers. I have added it back with the latest commit 29ec30c79f7ed1e1bb9b76dcbdaf4489c5351dbf. You should now be able to do things like

```
(var a @{})
(set a.0 :hi)
(print a.0) # prints :hi

**Comment by honix** [comment]
Hm.. Can we just disallow numeric keywords like ```:14``` and then fetch indexes with same syntax.
```
a:14 => get item with index 14 from a (or key 14 if a is a dict)
a:cat => get item with key :cat from dict a
a:"baa" => get item with key "baa" from dict a
```
Think indexed container is a dict with integer keys only.

**Comment by bakpakin** [comment]
I'll have to think about this some more. I agree that the current syntax is not general enough, but I also don't want to complicate the parser too much, nor incur a table lookup at runtime for using module functions.

I like the current way of handling modules by just merging the symbols from the loaded module into the current environment because it allows really flexible imports like `(import mymodule :prefix "")`, which is  like clojure's `use` (I realize this isn't well documented yet).

Right now, these shorthand syntax's are done in the compiler on a single symbol. This means that to the parser, all of these notations are just one symbol.

```clojure
(type 'a:b) => :symbol
(type 'hello.1) => :symbol
```

I think that this functionality should be in the parser, and the compiler doesn't need to know anything about the syntax. The `set` special form will still need to know how to act like a `put`, however. After
the parser creates a tuple, the runtime would need to treat data structures as functions that look up keys.

Some ideas:
```clojure
a:b => (a b) or (a :b) or maybe (get a b)
a.b.c.d => (a b c d) or maoybe (get a b c d)
a.b.c.1.2 => (a b c 1 2) or (a b c 1.2)?
a/"hello"/1.2e4/0x45 => (a "hello" 1.2e4 0x45)
a|b|"c"|:d => (a b "c" :d)
```
All of these have issues. Using a colon means keyword keys become different. A period is a valid
character in a number, so one could not have fractional numbers in such a form. The forward slash `/` is currently the division operator. The pipe `|` wouldn't have any collisions, but it looks a bit strange.

All together I think it would take several changes to get this to work as smoothly as possible. I think the steps would be

1. Allow calling data structures functions.
2. Update parser to support some infix tuple syntax
3. Update set special form to take a tuple returned by the parser as an lvalue.

This also has the benefit that each of these three steps is a useful feature on its own.

**Comment by bakpakin** [comment]
The latest commit now has working symbols, keywords, and data structures as functions.

```
(:a {:a 1}) # 1
({:a 1} :a)
```

I have been working on a lot of changes internal to the interpreter to simplify things a bit and deleting many lines of code. The external API should not have changed much be warned.

Also I have had a thought about how the set special could change. Perhaps the set special could take an lvalue that looks like the form that will retrieve the value like setf in other lisps, and remove the current shorthand. An example:

```
(def tab @{})
(set (tab :a) 1)
```

**Comment by honix** [comment]
Yay! Interesting, bi-directional logic here.

As I understand nested access will look like this:
```
((( {:a {:b {:c 1}}} :a) :b) :c)
```
And can be simplyfied by macro.

Love your choice towards simplycity.

**Comment by honix** [comment]
Yes, ```set``` form will work using same syntax.

**Comment by honix** [comment]
Seems number and string types can be added to funclike too:
```lisp
# arg access (all ok!)
janet:675:> ({'a 1 'b 2} 'b)
2
janet:692:> ({:a 1 :b 2} :b)
2
janet:709:> ({"a" 1 "b" 2} "b")
2
janet:729:> ('(1 2) 1)
2

# call access (number and string fails)
janet:740:> ('b {'a 1 'b 2})
2
janet:757:> (:b {:a 1 :b 2})
2
janet:774:> ("b" {"a" 1 "b" 2})
error in repl: attempted to call "b", expected function|cfunction
  (fiber)
    in _thunk [repl] at (775:793) (tailcall)
janet:794:> (1 '(1 2))
error in repl: attempted to call 1, expected function|cfunction
  (fiber)
    in _thunk [repl] at (795:804) (tailcall)
```

**Comment by honix** [comment]
I think, basicaly, this condition can be removed, janet_get will error back:
https://github.com/janet-lang/janet/blob/6f3bc3d577962b08c7143c007575ca8917588485/src/core/vm.c#L226-L229
Then there is no need for funclike. Or it is better to set funclike = indexed | dictionary. As they are actually callables here.
https://github.com/janet-lang/janet/blob/6f3bc3d577962b08c7143c007575ca8917588485/src/core/vm.c#L231

**Comment by bakpakin** [comment]
My thought was that not everything should be callable as a function as it might hide errors, but playing
around with it it seems that there is no issue. In fact it seems being able to call nil is useful in certain cases, like in looking values up in a map.

Updated in 2a79d2e.

**Comment by honix** [comment]
There is an idea to interpret "call" access as a call:
```
janet:24:> (def obj {:wof (fn () (print "wof-wof"))})
{:wof <function 0x00574D80>}

# call access
janet:63:> (:wof obj)
wof-wof
nil

# arg access
janet:74:> (obj :wof)
<function 0x00574D80>
```

**Comment by honix** [comment]
Yep! Closing.
