### ISSUE TITLE
Invalid arity error using janet -k

### ISSUE THREAD

**Issue by uoee** [janet-lang/janet#173]
Given

    $ cat triangle.janet

    (defn triangle-area
      [base height]
      (* base height 0.5))

    (triangle-area 1 2)

Compile, but don't execute

    $ janet -k triangle.janet

    compile error: nil expects 1 argument, got 2 on line 6, column 1 while compiling triangle.janet

But, when running as normal

    $ janet triangle.janet

No error (expected)

I also suppose the function name rather than the word "nil" would be better here (if that's straightforward to do).

**Comment by bakpakin** [comment]
This should be fixed as of d28925fdaba2998226038aebbd2d03c65f414001. The problem was a stricter function arity checker introduced in 1.4.0. We can get around it by not arity checking when the function is nil, which is what happens in a file when fly-checking checks a functions defined earlier in the file (the function definition was compiled but not executed, so the function is nil!).

**Comment by uoee** [comment]
Ok, thanks for the explanation. Perhaps in future the -k option could support these arity checks on function signatures in advance of running a program.
