### ISSUE TITLE
Interpret (key container) access as a function call

### ISSUE THREAD

**Issue by honix** [janet-lang/janet#18]
From issue #17.

```(container key)``` will get value of ```key``` from ```container```, if value is a callable to call we can try ```((container key) args)``` but this is little messy syntax.

So there is hacky solution:
```lisp
(key container args) => ((container key) args)
```

This makes key looks like method name, which is good to read, and drops one pair of parentheses.

Example:
```lisp
janet:24:> (def obj {:wof (fn () (print "wof-wof"))})
{:wof <function 0x00574D80>}

# arg access (get value)
janet:74:> (obj :wof)
<function 0x00574D80>

# call access (get and call value-function)
janet:63:> (:wof obj)
wof-wof
nil
```

Bakpakin's class example:
```lisp
# Create a 'class'
(def Car @{:honk (fn [self] (print "I am a " (self :maker)))})

# Create an 'instance'
(def mycar (table/setproto @{:maker "Subaru"} Car))

# Make a 'method call'
(:honk mycar)
```

**Comment by honix** [comment]
Argument example:
```lisp
janet:174:> (def obj {:wof (fn (n) (loop [:repeat n] (print "wof-wof")))})
{:wof <function 0x00542F18>}
janet:237:> (:wof obj 5)
wof-wof
wof-wof
wof-wof
nil
```

**Comment by bakpakin** [comment]
For the argument example, I think it is missing a self argument.


Also a little technical aside on why i think it will be easier to have the self argument for this syntax - a function call in Janet first pushes all of the arguments to a stack, and then invokes either the ‘call’ or ‘tcall’ instruction. This means when we make a call like

‘’’
(:wof obj 3)
‘’’

2 arguments are pushed to the stack. With the self argument, the two arguments are already exactly what we would expect, obj and 3, so the  vm can be more efficient and not have to move arguments around if the function turns out to be a keyword.

**Comment by honix** [comment]
But not every finction waits for ```self``` :(

**Comment by honix** [comment]
...But, yes, this ```(key container)``` notation can be used for "methods" with signature ```[self args]```. Say - method call shorthand.

**Comment by bakpakin** [comment]
I've just pushed a new branch keyword-oo that implements this. It was about 10 lines of code to add this functionality :smiley: 

See vm.c in d64a57297d3876bef36f39e8ec449ccdd60dba22

**Comment by bakpakin** [comment]
The introduction was meant to be more like a tutorial than a reference. I would rather write new docs for full coverage.

Agreed that the website needs these documents on it, will work on that eventually

**Comment by honix** [comment]
Got it!
