### ISSUE TITLE
jpm quickbin output segfaults when main has no arguments.

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#189]
foo.janet
```
(defn main [] 
  (print "hello world!"))
```
repro:
```
jpm quickbin ./foo.janet foo
./foo
Segmentation fault (core dumped)
```

**Comment by andrewchambers** [comment]
Note was janet 1.5.1

**Comment by bakpakin** [comment]
Hmm, should be an easy fix but oof

**Comment by bakpakin** [comment]
The problem was the main function expected 0 arguments, but was passed more. A simple fix is adding `&` to main like `(defn main [&] ...)`. The arity checking doesn't kick in when the arguments are passed directly to the stack via `janet_fiber` (which is arguably an API design flaw, as it lets you construct invalid stacks. Perhaps `janet_fiber` should not take parameters that push to the stack.) Anyways, simply using `janet_arity` fixes the problem and gives you a nice error message instead of a segfault.
