### ISSUE TITLE
Discuss: merge get and in semantics

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#203]
Recently 'get' was altered and an alternative, 'in' was added in this commit: https://github.com/janet-lang/janet/commit/aee168721548dd66502b3a37e6cab51595789b75

I think that having two functions doing nearly the same thing is not ideal for a few reasons.

- The 'in' function is implemented by the 'GET' opcode, which is confusing from an implementation point of view.
- The janet_get function now implements the 'in' logic from the C api side.
- The 'in' function is slightly more ambiguous when read than the original 'get' function.
- Calling a datastructure now has 'in' semantics rather than 'get' semantics which could be confusing.

Proposal:

Tweak the semantics of get to be as follows:
```
(get ds x) # throws an error on out of bounds.
(get ds x dflt) # Does not throw an error on out of bounds.
(in ds x) -> (get ds x) # in is now an alias.
(ds x) -> (get ds x) # current it matches (in ds x)
```

Discussion:

This change means the get semantics will once again match the CAPI function name, and the opcode name. It is also mostly backwards compatible.

Implementation notes:

`(get ds x)` Can be inlined as a single bytecode instruction after this change.

Drawbacks:
- churn on core semantics.

Counter arguments:

We should churn now if we have the desire to improve things, the change was relatively recent, code relying on this may be rare.

Future discussion:

The 'in' function is essentially alias, so could be removed, but it is not critical to do so.

**Comment by bakpakin** [comment]
The `in` function was a breaking change I added in 1.5.0 to make programs easier to debug without changing the semantics of `get`. `in` makes the data structures behave as though they have strict, data-structure-specific domains for keys, while `get` treats all data structures as associative arrays. (the current exception is abstract types, which behave however they want given a single getter function pointer). The reason a new function was introduced is that the behavior is different enough to warrant a new function. How `get` and `in` are implemented I consider to be a bit less important, but they should be fast in the common case (ideally not a full function call in the abstract machine). 

I really don't want to merge semantics because they are different semantics. I think you are focusing too much on both the opcode and the name `in`.

**Comment by andrewchambers** [comment]
I think in this case the janet_get function in the C api really needs to be named janet_in (or commented as such) , because that is what it now is. The user facing api does not match user expectation anymore.

I am also uncertain about what you consider the more idiomatic call, because the stdlib now exclusively uses 'in' instead of get. Is that a pragmatic decision to avoid breaking code? or should I always prefer 'in'.

**Comment by bakpakin** [comment]
Use of `in` is simply faster, and more importantly will catch more errors. When writing janet, I try to use destructuring over both `get` and `in`. boot.janet is written as it is for efficiency, not for any kind of compatibility. And yes, it changes the language from the C API perspective.

**Comment by andrewchambers** [comment]
Overall I think its a mistake to have 'in' be more efficient than 'get'. I feel like most users will intuitively use get. Maybe it won't matter and nobody will notice, but it seems backwards to me.

**Comment by bakpakin** [comment]
Wouldn't be hard to add both a `get` and `in` opcode. But It doesn't really matter what people use, as long as they use the core library things like `each` and `map` can be fast.

**Comment by andrewchambers** [comment]
Been discussed
