### ISSUE TITLE
Different output using anonymous tuple vs bound tuple

### ISSUE THREAD

**Issue by ryanford-frontend** [janet-lang/janet#213]
```common-lisp
(let [input [1 10]]
  (loop [i :range input] (print i))) ; 105

(loop [i :range [1 10] (print i)) ; 1 2 3 4 5 6 7 8 9
```

**Comment by bakpakin** [comment]
The first form is simply incorrect, it’s not how the loop macro works. The range isn’t evaluated as a tuple, it is expected to be a tuple literal of two or three values. It’s like saying `(let [x [‘a 2]] (let x a))` doesn’t work.

The main problem here is the first should be an error, rather than compiling. Instead, a symbol is treated as a sequence of bytes, so when we try to get the loop initializer, top value, and loop increment during macro expansion, we get the bytes of the symbol `input`, `i`, `n`, and `p`. this is why we see the number 105, it’s the ascii value of `i`. This is clearly incredibly surprising.

We should verify that the range is a tuple array during macro expansion to avoid this kind of form even compiling.

**Comment by bakpakin** [comment]
Thanks for the heads up, should be fixed. Closing.
