### ISSUE TITLE
module browsing functions for REPL.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#258]
`(all-bindings)` prints all bindings which are a huge list I cannot digest.

It would be cool to just print a module's bindings or the top bindings outside any module.

I would also like to see a list of available modules on REPL.

**Comment by bakpakin** [comment]
Try `(find (partial string/find "string/") (all-bindings))` to see all bindings for the string module.

In general, once a module has been loaded into the environment, its exports are just normal bindings like any other symbol. There is just a convention where imported symbols are prefixed with a "namespace". So to find all functions in the "string/" module, we just look for bindings that begin with "string/". This also works because functions that work on strings (like string/find) will usually work on symbols, keywords, and buffers as well.

**Comment by andrewchambers** [comment]
I think walking janet path, and finding all loadable modules might be a fairly complex operation, and probably would need a cache to be useful. this might be better as an external function.

**Comment by crocket** [comment]
Printing top-level bindings

```
(loop [s :in (filter |(not (string/find "/" $)) (all-bindings))] (print s))
```

Printing a module's bindings

```
(loop [s :in (filter (partial string/find "string/") (all-bindings))] (print s))
```

**Comment by crocket** [comment]
@andrewchambers Finding all lodable modules is not necessary. I just want to see subsets of `(all-bindings)`.

**Comment by crocket** [comment]
This is how I implemented my own module browsing functions.

```
(defn top-level-bindings
  "Return a list of top level bindings in (all-bindings)"
  []
  (filter |(not (string/find "/" $)) (all-bindings)))

(defn module-bindings
  "Return a list of bindings for a module in (all-bindings)"
  [module]
  (filter |(string/has-prefix? (string module "/") $)
          (all-bindings)))

(def- module-grammar
  (let [grammar '{:module-path (* (some (* (! "/") 1))
                                 "/")
                  :main (<- (some :module-path))}]
    (peg/compile grammar)))

(defn modules
  "Return a list of modules in (all-bindings)"
  []
  (let [module-name |(if-let [m (peg/match module-grammar $)]
                       (m 0)
                       nil)]
    (map |(slice $ 0 (- (length $) 1))
         (distinct (filter |(not (= nil $))
                           (map module-name (all-bindings)))))))
```

Do you want things like this in core or as a jpm package?

**Comment by crocket** [comment]
I created https://github.com/janet-lang/pkgs/pull/7 for this.
