### ISSUE TITLE
Minor improvements for REPL

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#267]
As I used janet built-in REPL, I discovered that it's better for Ctrl-U,  Ctrl-K, Alt-D, and Ctrl-W to behave as they do on GNU readline(rlrepl).

* It's more convenient for Ctrl-U to delete from the cursor to the beginning of the input line.
* It's more convenient for Ctrl-K to delete from the cursor to the end of the input line
* It's more convenient for Alt-D to delete to the end of the next word.
* It's more convenient for Ctrl-W to delete to the beginning of the previous word.

**Comment by bakpakin** [comment]
Rather than this back and forth on REPL keybindings, you may want to go in and add some yourself. The code is in src/mainclient/line.c, and you should be edit the `line` function to do as you need. Open a PR, and I will merge if everything is alright. I’m not particularly attached to the current keybindings, so as long as things aren’t buggy, I’ll probably merge the changes.

**Comment by crocket** [comment]
My C skill is rubbish, but I will try because this may not require proper C skill.

**Comment by crocket** [comment]
This issue is replaced by https://github.com/janet-lang/janet/pull/268
