### ISSUE TITLE
janet repl do not fflush stdout.

### ISSUE THREAD

**Issue by wsdjeg** [janet-lang/janet#278]
hello, and thanks for working for this project, and I just want to [add janet support in SpaceVim](https://github.com/SpaceVim/SpaceVim/pull/3330)

the code runner works well now, but the repl do not work in my plugin, as the janet do not fflush the sdtout buffer until we send `(os/exit)`.

![](https://user-images.githubusercontent.com/13142418/73654419-9e358d00-46c6-11ea-8159-3776209f6435.gif)

**Comment by bakpakin** [comment]
When programmatically interacting with Janet’s REPL, it’s useful to pass the ‘-s’ flag to the executable. Janet uses its own readline implementation which may not be expected by other tools. This flag disables that.

If that doesn’t work, you could try sending ‘(file/flush stdout)’ to the repl.

**Comment by wsdjeg** [comment]
> Janet uses its own readline implementation which may not be expected by other tools.

But if people who want to create repl plugin for vscode atom etc, all the plugin communicate with command line tools via stdout/stderr/stdin.

Is it possible add this feature in next release?

**Comment by bakpakin** [comment]
It should work fine in most cases, and I’m not even sure it’s your problem, just something to be aware of and some tools in the past had issue with it. It should work fine with stdout, stderr, and stdin. It’s also an easy fix -  use ‘janet -s’ instead of ‘janet’. 

We can probably just make the repl flush stdout and stderr on every top level form which may solve your issue as well. Usually, this will be done automatically on new lines by the terminal (in a line buffered stream). I wonder if spacemacs has this functionality built in to its repl handling.

**Comment by wsdjeg** [comment]
ok, I will have a try. thanks.
在 2020年2月3日 23:27，Calvin Rose <notifications@github.com>写道：

It should work fine in most cases, and I’m not even sure it’s your problem, just something to be aware of and some tools in the past had issue with it. It should work fine with stdout, stderr, and stdin. It’s also an easy fix - use ‘janet -s’ instead of ‘janet’.

We can probably just make the repl flush stdout and stderr on every top level form which may solve your issue as well. Usually, this will be done automatically on new lines by the terminal (in a line buffered stream). I wonder if spacemacs has this functionality built in to its repl handling.

―

**Comment by wsdjeg** [comment]
@bakpakin Thanks, janet support in spacevim has been done, and we use `janet -s` as default command to run repl.
