### ISSUE TITLE
Problem with sending a string from thread

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#287]
In this experiment: https://git.sr.ht/~pepe/scc.git I found some problem with sending my message. When I send a variable with a string Janet panics with: 

```
in thread <core/thread 0x55A74B9E6C20>: error: failed to send message <table 0x55A74B9D7E20>
```

Also occasionally Janet will SIGSEGV

But when I send the same string as literal, everything works as expected.

Can you please provide me with the direction where to look to debug this problem?

**Comment by pepe** [comment]
The offending code is https://git.sr.ht/~pepe/scc.git/tree/master/scc.janet#L31 (commented in the repository) and on the next line is the same message with string literal.

**Comment by pepe** [comment]
And the last thing :-). I am using the latest Janet source in time of writing https://github.com/janet-lang/janet/commit/8cb63cebbe0a7c705edc2162142a78adada7c6ca

**Comment by pepe** [comment]
I removed most of the cruft, for easier repro. Now the line is https://git.sr.ht/~pepe/scc.git/tree/master/scc.janet#L12

**Comment by bakpakin** [comment]
So you hit a rather thorny case here, which is actually all expected behavior.

The problem here is that you are trying to send a table which contains a function which indirectly references the current fiber (via a closed-over def, `s` in line 30. If you move. Janet disallows marshaling the current, alive fiber - a fiber must be paused before it can be marshaled so that is does not contain C stack frames.

Two points here:
 - You probably shouldn't send OO style tables with prototypes as messages - on receiving the message, the prototype table will be recreated per message, which defeats the purpose of prototypes. Instead, send plain tables as messages. Sending tables with prototypes still should work in many cases, though.
- Don't create closures and marshal them (or send them via `thread/send`, which internally marshals them) immediately. This is because a closure will reference the current fiber for as long as the any of the bindings it closes over live on the stack. In your case, the binding `s` lives on the stack until the closure it is defined in exits.

The solution:

```clojure
(def f (|(do
           (def s (string (:read f :all)))
           (fn [_ state] (put state :last-change s)))))
(:send m (e/make {:update f}))
```

Explanation:
This is kind of a limitation of Janet's bytecode - in the case where `s` is a var, we need to keep a reference to the stackframe in case the value `s` is update. Since `s` is declared as a `def`, however, one might expect that Janet could optimize this out, as we don't _really_ need access to the stack in this case. Janet as it is currently does not do this. This is an optimization that probably should be made, though.

**Comment by bakpakin** [comment]
Note: The sigsegv issue was indeed a bug and has been fixed. Limiting state capture of closures is a more difficult and harder to pin down issue. Marshaling functions and fibers will always have corner cases.

**Comment by pepe** [comment]
Thank you very much for this explanation. It helped me a lot with understanding what is going on. I thought that something like that could be a culprit. I will try to fix it this way and come back with the results.

Thank you for all the excellent work on Janet. It is highly appreciated!

**Comment by pepe** [comment]
Indeed it works the way you said. Again this is very eye opening.

**Comment by andrewchambers** [comment]
@bakpakin I wonder if marshal could just do the fiber detachment.

**Comment by andrewchambers** [comment]
@bakpakin I think if you are marshalling a closure, and see that the closure env is the currently alive fiber, I think it is possible to marshal it as if it were a detached env.

**Comment by bakpakin** [comment]
That's probably true, I think we could also extend that logic to the garbage collector to help in some cases.
