### ISSUE TITLE
+= etc macro's don’t work with dynamic bindings

### ISSUE THREAD

**Issue by wboeke** [janet-lang/janet#310]
The += macro's etc (in boot.janet) contain function (set .. ). This should be (setdyn ..). Btw, if I modify boot.janet and re-compile, make crashes, leaving an empty janet.c file ...

**Comment by bakpakin** [comment]
One, the macros work fine, they just don’t work directly with dynamic bindings. Two, if make is crashing, your changes to boot.janet  are probably invalid and geothermal don’t compile or do something wrong. Janet precompiles boot.janet and splices the bytecode into the output, so that would be why you don’t even get any output from janet.c

**Comment by andrewchambers** [comment]
@wboeke I think you have misunderstood how dynamic bindings in janet work.

**Comment by bakpakin** [comment]
dynamic binding means dynamic scope, not mutable bindings. The "+= macros" are intended for vars. Closing as wnf.
