### ISSUE TITLE
How valued will backwards compatabilty/language stability be?

### ISSUE THREAD

**Issue by ahungry** [janet-lang/janet#322]
I notice code I wrote some time ago (janet) no longer ran after updating from 1.3 to 1.7 (I guess some problem with the old import system allowing default names like foo/bar/baz for a symbol from (import foo/bar).

Also, janetsh library seems unable to run on latest janet.

https://github.com/andrewchambers/janetsh

In clojure and most other lisps, there seems to be a very strong adherence to minimizing backwards compatability breakage.

When (if ever) do you view janet as being "stable" - to where I could write code, and plan to have it remain as valid Janet code 10 years later?

**Comment by andrewchambers** [comment]
fwiw, janetsh is not a library, the same way nodejs is not a library. That being said, its a valid point.

**Comment by andrewchambers** [comment]
@ahungry Another point that comes to mind. As the janet stdlibrary is written using the C standard library, which is stable. You are free to bundle the janet amalgamation with your software, this is likely to work for the next 10 years.

**Comment by bakpakin** [comment]
I have been trying to be better about this, and in general will be more resistant to “fixes” going forward, 1.8 onwards. When new people come to a project, they bring external perspective and usually valid suggestions and “improvements”, which are often backwards incompatible. I have been too eager to take these in and break things, as there have been a number of releases that break things since 1.3.

At some level, full backwards compatibility is incompatible with good interfaces, so there may be subtle breaking changes in the future - in truth, almost all changes are breaking. Many times, these are just changes that make janet behave more like a familiar language, like python. I will try and be resistant to those kinds of changes.

It is not my intention to break things, but it will happen unfortunately. Many python codebases will break on new versions of python,  node js versions, or even browser versions nowadays.

I have tried to mitigate this somewhat by adding tests for some jpm libraries in the ‘make test-install’ target which runs all tests for a set of libraries in CI for each version of Janet, like argparse and JSON, but there are currently only a handful that run here.

**Comment by andrewchambers** [comment]
I have a fairly large number of janet tests we could integrate.

**Comment by bakpakin** [comment]
One criteria for tested libraries I have right now is running on both windows and Linux, but I think practically we need to relax that as not a lot of people seem to be contributing Windows compatible code. Open a pr with your added repo, should be easy to modify the Makefile.

**Comment by andrewchambers** [comment]
It is my strong opinion we should do a slow and considered review of the current state of the std library before declaring them stable.

**Comment by andrewchambers** [comment]
#323 is a perfect example of this issue. It is clear to me symlinks are a more useful default, this is what the documentation suggests, but fixing it is a breaking change.
