### ISSUE TITLE
Release 1.8.1 under windows 10: jpm.bat fails to run 

### ISSUE THREAD

**Issue by EmmanuelOga** [janet-lang/janet#343]
I unzipped the x64 windows version from the releases: https://github.com/janet-lang/janet/releases/tag/v1.8.1

When I try to run jpm I get:
```
PS C:\janet-1.8.1> .\jpm.bat
error: could not find file C:\janet-1.8.1\\jpm.janet
  in dofile [boot.janet] on line 2177, column 5
  in cli-main [boot.janet] on line 2443, column 9
```

Noticing there was a jpm file on the folder that seems to be the source of the package manager, i ran:
```
PS C:\janet-1.8.1> .\janet jpm
error: expected integer key in range [0, 0), got -1
  in last [boot.janet] on line 651, column 3
  in _thunk [jpm] (tailcall) on line 101, column 12
```

... which triggered that other error

**Comment by pepe** [comment]
I think the second problem could have been caused by this https://github.com/janet-lang/janet/pull/340

**Comment by bakpakin** [comment]
Did you try the installer? The zip file simply contains all of the files, but does not set anything up, such that external package managers or scripts can automate installs. janet.exe will work without any setup, but jpm will not.

**Comment by EmmanuelOga** [comment]
Hi, just installed with the x64.exe installer and the system works now.
The .zip file seems to not contain the same folder structure, so I'm a bit confused what's the use for it

**Comment by bakpakin** [comment]
The use is for external systems or scripts to have more control over setting up a Janet environment, or for adding components to a system that does not want to use jpm. For example, a scoop or chocolatey package could probably work better with the zip file rather than the NSIS installer. The folder structure isn't that important, as the installer also needs to set environment variables.

**Comment by EmmanuelOga** [comment]
got it makes sense
