### ISSUE TITLE
makefile-like recipes in JPM?

### ISSUE THREAD

**Issue by PaulBatchelor** [janet-lang/janet#364]
Is there a way to write something analogous to makefile recipes with JPM?

I'm writing some native janet plugins using a literate style, which means that C code needs to be generated before it can be compiled. In Make, I have recipes that automate this process.

At the moment, my solution has been to wrap JPM calls inside a Makefile, but it would be great to use the Janet ecosystem instead.

**Comment by bakpakin** [comment]
Yes, you can do that with jpm.

Internally, all declare statements just generate a bunch of rules that behave like makefile rules, which you can manually declare.

To make a rule:
```
(rule “output.txt” [“dep1.txt” “dep2.txt”]
  (spit “output.txt” (string (slurp “dep1.txt”) (slurp “dep2.txt”))))
```

This should behave more or less like a make file rule to create output.txt that updates when dep1.txt or dep2.txt are changed. For a rule that behaves like a phony rule, use ‘phony’ instead of ‘rule’. Rules can be run via jpm run (rule).

**Comment by PaulBatchelor** [comment]
perfect. thanks!

**Comment by PaulBatchelor** [comment]
@bakpakin is there any equivalent for pattern matching recipes using "%"?

**Comment by bakpakin** [comment]
There is not. However, because we can generate rules programmatically, you can iterate over targets and generate rules.
