### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [janet-lang/janet#39]
I suggest to reuse a higher level build system than [your current make script](https://github.com/janet-lang/janet/blob/06f38d33802857765efca0a16e7c8eca3ccc0777/Makefile#L22 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by bakpakin** [comment]
I used to have a CMake script for building Janet, which I then deleted as it was annoying to maintain and less flexible than a Makefile. I found CMake to not really be an improvement for portability. I do miss the easy development on Windows with visual studio, but a batch file works fine too.

A supplementary CMakeLists.txt for building would be useful, but not really on my roadmap.

**Comment by elfring** [comment]
How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.14/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by bakpakin** [comment]
Build system generators are nice sometimes, but don’t really help with making things truly cross platform, they just smooth out the easiest step. Since I do most of the development for Janet in vim on Linux and occasionally Notepad++ on windows, IDE support is not so important to me.

Lastly, Janet has a bootstrap step that requires somewhat complicated rules. The CMake build, even before when it was simpler, required several custom commands to embed files in the binary.

Again, a CMake based build would be great and definitely help developers who wanted to use an IDE contribute, but not on my Roadmap. As for making Janet cross platform, I don’t think a build system generator is all that much help besides setting a handful of compiler flags, especially as Janet has basically no dependencies besides some basic Posix stuff and win32 on windows. Possibly pthreads in the future.

**Comment by elfring** [comment]
Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?

**Comment by bakpakin** [comment]
No.
