### ISSUE TITLE
Question: purpose of quote in disasm output

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#405]
What is the purpose of this line?

https://github.com/janet-lang/janet/blob/b7cfc08fc5fefc4f003d140bcd962dadd88ec8bc/src/core/asm.c#L889

Why do you need a quote here?

**Comment by bakpakin** [comment]
The original idea (I think) was to have the output of disasm be printable and then readable by the parser and evaluated. This is also very old code, before keywords and various other types. I think we should probably remove that, although the output of disasm could well by change to use keywords instead of symbols for keys in the returned struct.

**Comment by bakpakin** [comment]
Ah looking more at the code, it seems `asm` supports named constants, so we needed some way to distinguish `(def a 10)` (a constant 10, as well as an alias "a"), and `(quote (def a 10))` (the actual tuple). I think we can remove this "feature" of asm, as it is not documented, used, or even particularly helpful. I had originally thought I would need to write some Janet assembly to boot strap things, but that wasn't so much the case besides some core forms assembled in C.

**Comment by andrewchambers** [comment]
Thanks for the explanation,
