### ISSUE TITLE
`loop ... :generate` doesn't play nicely with destructuring

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#428]
My mental model of the `:generate` verb in the `loop` macro is: 

> repeatedly resume the provided fiber and call the body of the loop with the result. When the fiber is exhausted, exit.

Similarly, I would expect to be able to do destructuring/binding in the left side of a `:generate` invocation inside of a loop.

Both of these work normally, however they do not compose. 

Minimal example:

```clj
(defn f []
    (yield {:a :ok}))

(loop [{:a x} :generate (fiber/new f)]
      (print x))
```

Expected output:
```
ok
```

Actual output:
```
ok
error: expected string|symbol|keyword|array|tuple|table|struct|buffer, got nil
  in _thunk [scratch.janet] (tailcall) on line 4, column 1
```

When a fiber is exhausted it returns `nil`; it seems to me that the `nil` check inside the `loop` macro is happening *after* the attempt to destructure the result, when in fact I would expect it to happen first, and to short-circuit any destructuring just as it short-circuits the loop body.

**Comment by bakpakin** [comment]
Thanks for finding this, not much to say here besides what you have already said. Since janet's compiler is so simplistic, the loop macro tries not to create extra bindings unless it needs to (when the l-value is a symbol, no need to create an intermediate def). This "optimization" is correctly applied to other loop verbs, but for generate it is always on, which leads to bad behavior. We just apply the optimization to this particular verb.

**Comment by subsetpark** [comment]
Thank you!
