### ISSUE TITLE
`make install` does not respect PREFIX

### ISSUE THREAD

**Issue by tekknolagi** [janet-lang/janet#44]
It looks like `make install` does not respect the `PREFIX`, particularly when installing the man page to `/usr/local/...` and tools to `JANET_PATH`. This is not ideal; I'd like to have an installation of Janet in my `~/.local` folder.

**Comment by bakpakin** [comment]
I have just pushed a fix that should help with that in the latest commit d2d502b9ae9e22c397f73b4af708b574d075e592. It also removes the automatic installation of the shared library `libjanet.so` as well, as that is by nature less portable and not needed to run janet.

**Comment by bakpakin** [comment]
The correct default JANET_PATH should now also set a build time as of 540b326c547e05a780358717c54f90aca9f543f3. Hopefully this should fix the problem.

**Comment by bakpakin** [comment]
Sorry about this whole issue, JANET_PATH was not being read at runtime at all, and the documentation in the man page was out of date. This was because the core library up until recently was basically evaled every time the janet binary was run - there was no bootstrapping step.

I have been working on some updates to this and made the following changes:

* Setting `PREFIX` or `JANET_PATH` at build time will set the default JANET_PATH. This should make local insalls work better out of the box
* Setting `JANET_PATH` on the command line via something like `JANET_PATH=examples janet` should work correctly. Something like `JANET_PATH=examples build/janet -l colors` should load the colors module.
* The -m flag has been added as well, which does basically the same thing as setting JANET_PATH
* Update the man page and changelog to reflect these changes

**Comment by tekknolagi** [comment]
Wow, thank you for your quick and comprehensive fix!
