### ISSUE TITLE
Configurable allocator

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#486]
Perhaps just macros to provide JANET_MALLOC, JANET_REALLOC and JANET_FREE would be enough.

**Comment by EleanorNB** [comment]
May I humbly suggest an alternative API: instead of malloc(), realloc(), and free(), alloc() and resize(). alloc() works like malloc(); resize() works like realloc() if the new size is not zero, and if it fails the caller can attempt an alloc() instead; resize() with zero always succeeds, and works like free(). This is the allocator interface adopted by [the Zig programming language](https://github.com/ziglang/zig), and it has served us very well.

(Yes, the three-function interface is more symmetric with C -- however, if we adopt an official language spec a la #542, we may not want that.)

**Comment by andrewchambers** [comment]
This has been added in a simple form.
