### ISSUE TITLE
Using iterators to iterate over data structures

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#535]
## Proposal

Janet iterates over data structures by using a combination of calls to `next` and `get`/`in`. This works well for indexed data structures but less well for other types of data structures (notably dictionaries). I'd like to propose iteration be accomplished using iterator objects. 

## Problem

The core API includes a variety of macros and functions that rely on iteration (e.g `each`, `loop`, `map`, `reduce`, `filter`, etc). These constructs are defined in `boot.janet` and are implemented in different ways but the fundamental idea is that the data structure is asked to provide the 'next' index (either the 'first' index if a `next` instruction is executed with no previous index or the following index if a `next` instruction is executed with the previous index). The index returned is then used with the `get` instruction, to 'get' the value at this index.

This is an elegant implementation and has the virtue of simplicity. Unfortunately, its limitations are apparent in data structures that are not typically thought of as being 'indexed' (notably dictionaries like tables/structs). A simple example:

```
(each val ds
  (pp val))
```

If `ds` is `{:a 1 :b 2}` A user might expect that `val` would be a tuple of key-value pairs. However, this is not the case. Because of the implementation, `val` will be a value of `ds`. This is apparent from the documentation but is not intuitive.

As a workaround, some of the constructs include variations (e.g. `eachp`) or options (e.g. the `:pairs` keyword) that allow a user to pass in a dictionary. These work adequately but do not exist for all constructs. For example, there is no version of `map` that can iterate over a dictionary. The alternative in these situations is to use `pairs` to transform the dictionary into an array of key-value pairs. This adds complexity.

## Solution

Rather than use `next` and `get`/`in` on a data structure, a data structure could be asked to return an iterator that is then used by the iterating constructs to iterate. The iterator would maintain the state of its current index and would be responsible for returning the value requested.

## Drawbacks

The solution has the following drawbacks:

- **Breaking change**. In a technical sense, the iterating constructs would not operate the same way in respect of dictionaries. I am doubtful given the unintuitive nature of the current behaviour that anyone really uses the iterating constructs with dictionaries in the current way, though, so I think this would be acceptable.

- **More C**. Adding an iterator object would increase the amount of C code. Given C's history, this expands the surface area for vulnerabilities and memory leaks.

- **More abstractions**. Conceptually, iterators adds an additional abstraction to iteration. To the extent that the simplicity is a goal of the implementing C code, this would act in opposition to that that. This is somewhat ameliorated by simplifying the implementing Janet code.

**Comment by bakpakin** [comment]
As presented, this is a WNF for all of the reasons you have listed. Also in terms of efficiency, iterating over `(pairs my-dict)` isn't much worse than creating a key-value pair on each iteration of the loop. There are other places where iteration being the combination of `next` and `get` is annoying, namely iterating fibers, but there are workarounds for that.

Even without using `get`, I would prefer an iterator that was based on `next` as it gives the option for stateless iterators. Simply requiring that iterators be stateful is a no-go. Iterating over elements in an array should _not_ allocate.

The option for stateful iterators defined in Janet though is appealing and could be implemented by either:
 * defining `next` and `get` for an existing type that encapsulates deferred computation (closure or fiber)
 * Have an abstract type that allows user overrides for `next` and `get`.
 
 I actually prefer the first, since the runtime cannot yield or signal over the methods of abstract types.
 
 For fibers, `next` could be defined as
   (next fiber _) would return the fiber if it can be resumed, nil otherwise.
   (get fiber x) could be defined as `(resume fiber x)`.
   
 Fibers would then be usable as stateful, custom iterators that could be mapped over, etc. There may be some combinators that also use the `(length)` function to try and do things like pre-allocate space that may need to be addressed.
 
 Note that the current behavior for tables and structs will not change.

**Comment by pepe** [comment]
Little OT, but I like the idea of (next fiber _) for my never-ending attempt to create reactive streams for Janet. Especially the "custom iterators that could be mapped over" part I find interesting. Thanks.

As for iterators, I have never used them outside places, where it is the only way (eg. LevelDB). I like the simplicity of `next` better (not only in Janet).

**Comment by pyrmont** [comment]
@bakpakin Thanks for the considered response. I confess I'm a little unclear on how the deferred computation approach would work but am still thinking about it. Having a way to create stateful, custom iterators would be cool.

Given this is WNF for the specific approach proposed here, I'll close the issue.
