### ISSUE TITLE
Windows: net/read sometimes fails

### ISSUE THREAD

**Issue by dracconi** [janet-lang/janet#568]
Following code sometimes works, sometimes doesn't.
`net/read` errors with `error: The attempted operation is not supported for the type of object referenced.`, but sometimes returns correctly.

```clojure
(defn exchange
  "Exchange data over TCP."
  [host port data]
  (when-with [s (net/connect host port)]
    (net/write s data)
    (net/flush s 0)
    (net/read s 4000)))
```

I'm not sure how consistent it is, but it seems as if it fails only at the beginning -- later something 'clicks' and then it doesn't fail as often (or at all?).

~~Could only reproduce this in REPL so far.~~ Ok, also doesn't work in compiled file.

Drop-in solution seems to be using `ev/read` instead of `net/read`, so far it hasn't failed in my experiments.

**Comment by bakpakin** [comment]
Interesting find, indeed locally using `ev/read` instead of `net/read` fixes the issue. Looking at the code, virtually the only difference between these two calls on windows is `ReadFile` for `ev/read` vs `WSARecv` for `net/read`. I'm curious to see why `WSARecv` is failing here but ReadFile is not.

**Comment by bakpakin** [comment]
This has been addressed on master by using ReadFile instead of WSARecv for reading from streams, as well as a few other changes.
