### ISSUE TITLE
os/execute leaks files passed in to stdout/stderr on windows

### ISSUE THREAD

**Issue by yumaikas** [janet-lang/janet#593]
To reproduce for stdout, run:

```
(def outfile (file/open "unique.txt" :w))
(os/execute ["janet" "-e" "(pp (seq [i :range (1 10)] i))"] :p {:out outfile})
(file/flush outfile)
(file/close outfile)
(os/rm "unique.txt")
```

This leads to "permission denied: unique.txt".

Looking at things in resource monitor, janet is leaking a reference to unique.txt. I've tested that file/close works as expected, so I believe os/execute is at fault here.

**Comment by bakpakin** [comment]
So what is happening here is that os/execute creates an unneeded stream copy of stdout. This is done for `os/spawn`, since the processes handle returned by os/spawn has `:in`, `:out`, and `:err` being streams not files. However, this is not needed for `os/execute` and just creates extra garbage.

This can be verified by adding `(gccollect)` before the call to `(os/rm "unique.txt")`, and everything should work as expected.

**Comment by yumaikas** [comment]
Thanks for getting this fixed so quickly!
