### ISSUE TITLE
(unintuitive behaviour) Method syntax on dictionaries "leaks" key semantics

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#596]
This isn't a bug, and I wasn't exactly surprised to see it, but I do think it has the potential to produce confusing or hard to reason behaviour, so I thought I'd at least document it.

One of Janet's convenient syntax features is that indexing syntax works in either position.

```
repl:24:> (def ind [:ok])
(:ok)
repl:25:> (ind 0)
:ok
repl:27:> (0 ind)
```

This is the case for non-associative structures, but for dictionaries, position is more meaningful. Given some object:

```
repl:21:> (def obj @{:status :read :read true})
@{:status :read :read true}
```

The only way to perform normal attribute access is with the object in the operator position:

```
repl:22:> (obj :status)
:read
```

If the object is called with a keyword in the operator position, that's treated as a method call; a call like `(:foo obj)` is translated into `((obj :foo) obj)`.

However, this translation happens even if the attribute at that keyword is *not* a function. Therefore, if an object is called with a keyword in the operator position, and that keyword is associated with a value that is *also* a key in the object with some value *val2*, **the value of that expression will be *val2*.** Here's an example:

```
repl:21:> (def obj @{:status :read :read true})
@{:status :read :read true}
repl:22:> (obj :status)
:read
repl:23:> (:status obj)
true
```

When I try to get `:status` from the object, I get the keyword `:read`, as I'd expect. However, when I invoke `(:status obj)` - either because I think it's a function or because I don't realize that there's a difference in the semantics of position for dictionaries - it's actually translated into a call like `(get obj (obj :status))`. In this case, the value of `:status` at obj (which of course could be anything) also happens to be a key in the object. However, as user of the data structure I probably don't know ahead of time what the value of `:status` is, so it could be quite surprising indeed when I get `true` out on the other side.

**Comment by bakpakin** [comment]
> One of Janet's convenient syntax features is that indexing syntax works in either position.

Not really. It is simply any value can act like a function, and some values look themselves up, and other types look up there first argument.

I don't currently plan on fixing anything here - this is just a consequence of keywords acting as method selectors when called instead of looking themselves up.  This is all completely intentional, and I don't know if you are suggesting a solution or not so let me make a few suggestions:

- Don't use (key data structure) to look up things unless you know types. It's a shorthand that only works on some types. `(keyword obj)` is documented as a method call.

If you were suggesting that keywords should look themselves up like in Clojure, you are not the first but I don't plan on adding that.
