### ISSUE TITLE
Reading from fiber of `os/spawn` caps on 4096 chars for swaymsg

### ISSUE THREAD

**Issue by pepe** [janet-lang/janet#610]
Simple repro with `swaymsg`:

```
(def p (os/spawn ["swaymsg" "-t" "get_tree"]
                               :p {:in :pipe :out :pipe}))
(:wait p)
(length (ev/read (p :out) :all))
4096
````

With `wc`:

```
swaymsg -t get_tree | wc -m
43422
```

It could be I am doing something wrong.

**Comment by pepe** [comment]
WIthout the pipe, spawn prints the whole message.

**Comment by pepe** [comment]
I just found a pipe output buffer set to 4096, and if I continue to read, I got all the content. I will leave it open for another day or two after I close it, just FYI. Feel free to do it yourself.

**Comment by bakpakin** [comment]
Looks like a bug, `(ev/read x :all)` should reads in chunks of 4096, but it seems it is giving up after the first one.

**Comment by bakpakin** [comment]
So, in general, you should wait on a process _after_ you do all IO on it. The tests in suite009.janet are to make sure that we are still able to read the bytes remaining in the pipe after the child process closes, but since pipes don't have an unlimited buffer size, this will not work in general.

In your case though, it should work fine since 43422 < 65536, the default size of a pipe's buffer on linux (assuming you are on linux). I have a fix locally that continues calling `read` after getting POLLHUP instead of exiting immediately.

**Comment by bakpakin** [comment]
So simple local fix:

```
(def p (os/spawn ["swaymsg" "-t" "get_tree"]
                               :p {:in :pipe :out :pipe}))
(length (ev/read (p :out) :all))
(:wait p)
```

**Comment by pepe** [comment]
Thank you. I understood it the other way, first `:wait` for the process then `read` process' `:out`.
