### ISSUE TITLE
uint64 & int64 Typed Arrays

### ISSUE THREAD

**Issue by jfcap** [janet-lang/janet#67]
Since 0382dc9 commit, uint64_t & int64_t typed arrays support have been removed.
Why ?
I know we don't have (yet ?) full proper way to manipulate 64bit integers directly in janet (without truncation) but a lot of numerical C libraries use 64bit integers arrays and it's handy (and efficient) to be able to pass directly such binary data as "standard" janet objects to them.

**Comment by bakpakin** [comment]
I removed them because there is no way to manipulate them, and likely never will be. If you read the JavaScript standards for typed arrays, they don't include 64 bit integer support at all for this reason. I was alerted to the problem via warnings in the Microsoft compiler on Appveyor.

Considering how easy it is to add them back, we can add them if we ever support proper 64 bit integers, maybe via some boxed representation (core/bigint?)

**Comment by jfcap** [comment]
Here a bigint  implementation proposal.

https://github.com/jfcap/janet.git (branch bigint)

It's not finished. 
But at this point, some feedbacks are welcome.

```
janet:0:> (def a (bigint/uint64 0xfff))
4095
janet:30:> (def b (bigint/uint64 "0xffffffffffffffff"))
18446744073709551615
janet:75:> (:/ b a a)
1100048695360
janet:86:> (:- b (:* a 2))
18446744073709543425
janet:102:> (type a)
:core/uint64
```



TODO :
    * marshal/unmarshal
    * more operators (bitwize operations ...)
    * ... ?
    * adding typedArray (u)int64 back ;-)
   

some tests are available in suite6.janet
