### ISSUE TITLE
How did Janet become so reliable and bug-free so quickly?

### ISSUE THREAD

**Issue by elimisteve** [janet-lang/janet#684]
Would @bakpakin mind talking about the strategy used for creating Janet? Did you only merge in features once they were pretty perfect rather than creating a working prototype ASAP? Other young languages seem much buggier, but my (limited) experiences with Janet have been very positive.

As per #542 , a language spec wasn't created first, which seems practical to me, by experimenting to see what feels right and _then_ making things more formal later. So that wasn't part of how Janet got so far so quickly.

How'd you do it, and what would you recommend to other language designers/creators/implementers?

Thanks!

**Comment by bakpakin** [comment]
I'd be happy to answer to the best of my ability - I'm glad your experience with Janet has thus far been positive! 

Language specs can be quite useful, but any programmer would need at least a mental "spec" to write a compiler or interpreter - Janet is no different, and although we don't have a spec, we do have documentation that serves as an informal spec. Janet is simple enough that much was coded in a fairly straight-forward manner to get the features that I wanted, and data structures are represented in memory much as how they are presented in code - there is not too much fancy stuff going on behind the scenes (with the exception of closures and fibers). If I did everything over again from the start, I would write a spec, though.

As far as "other young languages seem buggier", that usually means that the language is either trying to tackle a much more challenge domain (i.e., high performance, complex type system), has a poor quality implementation, or both. I don't think there is any secret sauce other than general good coding practices. Also being wary of new features, edge cases, and complexity is a good idea (unless your domain is performance). Assuming that your languages does at least some tricky things in the implementation, tackle those things first - In Janet, the first things that were tackled in the implementation were closures, fibers, and the garbage collector, which were the most complex, essential pieces of the runtime.

Any new language promising fast compile times, fast binaries, and a rich type system all the same time should make you extremely skeptical.

As for the language, start with a prototype. The prototype for Janet was Fennel, which was written in Lua so the language "feel" and compiler could be prototyped out. Fennel is now a micro-lisp in it's own-right, although the compiler has since been re-done and is now self-hosted.

Languages like Lisp, FORTH, and APL are great for a first implementation because they let you get through the parsing/lexing stage rather quickly - these are the stages the newbies get hung up on but can easily be changed later as you design the semantics of a language.

Single pass compilers are harder to make/implement than multi-pass compilers! This didn't really hurt/affect Janet all that much, but is rather counter-intuitive to some people.

Also, don't skip the fundamentals. Read a book on compilers and languages, write a simple language before a complex one, and don't try an pack in every fancy new idea into one language - it will implode.

**Comment by uvtc** [comment]
Does Janet have a single-pass or a multi-pass compiler?

**Comment by andrewchambers** [comment]
There have definitely been bugs, and some have been fairly serious - but they have always been fixed quickly on reporting.

**Comment by bakpakin** [comment]
> Does Janet have a single-pass or a multi-pass compiler?

Janet has a single pass compiler, which is not ideal. Since optimization is not much of a goal here, though, it works fine.

**Comment by bakpakin** [comment]
Closing this. If further discussion is wanted, create a Github discussion or ask in the matrix chat.

**Comment by elimisteve** [comment]
@bakpakin Thank you!
