### ISSUE TITLE
A trailing backslash as linebreak in function docstring.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet#694]
```
(def func
  ``
  line 1\
  line 2
  ``
  []
  (print "aa"))
```
```
$ (doc func)
line 1
line 2
```

**Comment by sogaiu** [comment]
This ability is nice to have.

I learned today that another way is to use two or more spaces.  This appears to be mentioned in the common mark spec as well: https://spec.commonmark.org/0.29/#hard-line-breaks

Is this feasible / easy in janet?

**Comment by crocket** [comment]
Even if it was feasible, I think `\` is better than trailing spaces.

**Comment by sogaiu** [comment]
One nice thing about using spaces is that some people might find that easier to read in the unrendered form compared to a backslash.  Possibly, some folks might find that to be more in line with one of the goals of Markdown:

> Readability, however, is emphasized above all else. A Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions. 

Granted there is some subjectivity here, but personally I find the two or more spaces that would be invisible in source form to be easier on my processing (by being invisible) compared to a backslash, which if present I think counts more like "it's been marked up with a formatting instruction" by being visible.

Perhaps you could elaborate on why you think `\` is better than trailing spaces.

**Comment by crocket** [comment]
Invisible trailing spaces are confusing. You don't know whether or not they are absent.

**Comment by sogaiu** [comment]
Thanks for sharing.

**Comment by uvtc** [comment]
I too think having two trailing spaces = a newline is not a good idea, and am surprised it ever made it into any markdowns. As @sogaiu points out, md is foremost about readability. And, by definition, you can't read two trailing space because they're invisible.

Not to mention that folks may have their editors configured to delete trailing whitespace.

The trailing backslash is an *ok* compromise, and I think pretty commonly used and understood one, even though it doesn't visually look like what it means.

That said, instead of manually adding newlines to your text content, you may find that your text might be better written as a list or a code block. Another option is to put in a raw `<br/>` (if targetting html).

Pandoc has a "line block" syntax:

~~~
| John Smith
| 42 Pine St.
| Springfield, MA
~~~

which I actually think is a mistake --- I think that beautiful pipe prefix should've been used to indicate a div, but that's an old conversation in a different repo. :)

**Comment by sogaiu** [comment]
Thanks for your thoughts.

It's interesting to see what different people value.  I find the backslash to interrupt my processing and it feels distracting to me (whereas two or more spaces by being invisible do not), but clearly that's not an issue for other people.  Perhaps these sorts of differences were accounted for in deciding whether to have more than one method to achieve linebreaks.

I don't know what the history of editors being configured to automatically delete trailing whitespace is like, but FWIW, I don't typically configure my editor that way.  I tend to go over my staged content in detail before committing so often catch things that way.

All this said, I am fine with the existing situation.  I also think there is value here in less code / complexity.

(I brought this point up because there was another person who felt similarly about a preference for two or more spaces over a backslash.)

**Comment by crocket** [comment]
By the way, janet.kak automatically removes trailing spaces.
