### ISSUE TITLE
Proposal: Option to build without floating point support

### ISSUE THREAD

**Issue by EleanorNB** [janet-lang/janet#715]
The idea for this proposal came to me from <https://stackoverflow.com/questions/4448835/alternatives-to-lua-as-an-embedded-language>. As usual, I recognise my knowledge of Janet is limited, and I may simply not be aware of an existing solution.

Janet uses integers internally for many purposes, but does not expose these as a type. This means that most numeric operations must be performed on floats, including operations that only make sense on integers, like indexing and bitwise operations. Not only is this ugly, it also means that Janet cannot be used on platforms with no floating point support, including most microcontrollers.

Lua has had the option to use any numeric type as the generic "number" for many years, and more recently added full integer support to the default build; our design means we will not be able to do that directly, but I believe we can get some of the way there.

I propose a new directive, `JANET_NO_FLOAT`, that will replace the role currently served by doubles with 52-bit signed integers (32-bit on 32-bit platforms). The upper 12 bits will be used for type info; this gives us the memory savings of NaNboxing.

I chose these bit widths as they are the precise maximum address width of their target platforms (of which I am aware). This was an arbitrary decision; up to 60 bits could be achieved, but I personally do not see a need for that, given that doubles start to lose precision within a few binades of this range anyway. If `JANET_NO_NANBOX` is also defined, full 64-bit integers become possible.

**Comment by GrayJack** [comment]
I think once Janet had integer as "native" type and it was later remove in favor of integer as abstract types. But I'm no know for a good memory 😆 , so I'm not sure my memory is correct.

**Comment by bakpakin** [comment]
The decision was made because you realize implementation blows up if you have to implement every combination of [float,int] op [float,int] for every binary operand (about 4x as much implementation). You can make this easier with some general conversion rules but it still a bit of a mess with many caveats.

It wouldn't be too difficult to add such a compilation flag, but we would likely need to go through the code and address many uses of `double` in function signatures, as well as change the marshalling protocol, etc. And realistically any CPU that can run Janet has an FPU. Yes, I've used builds of Lua on micro-controllers (ESP32) that had integers but no floats, but frankly I didn't find it too compelling. Such devices were so memory constrained that the interpreter occupied the majority of memory leaving you space for only the tiniest of simple programs.

**Comment by EleanorNB** [comment]
Whoof, that's a lot of issues. Some micros today can run Python, so I'm not greatly concerned about that point, but everything else together is a breaker.
