### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by yvendruscolo** [janet-lang/janet#75]
Are there plans for threading or concurrency of any kind?

**Comment by bakpakin** [comment]
There are some plans in the future to add some unspecified point in the future to add thread based concurrency with pthreads on Posix, and windows threads on windows. Each thread would run a separate interpreter and would not share memory. Threads would communicate through channels that use Janet’s marshal/unmarshal functionality to move data from one thread to another.

I had a local version of this working, but I postponed it for a while to work on other things. The method discussed above is very easy to implement because it would not require changing any existing code. Anything with shared memory, however, will need a thread-aware garbage collector, among other changes. I’m also not sure exactly what the API should look like. I would to be a bit smarter than just thinly wrapping pthreads, especially given the no shared memory caveat.

Also note that Fibers can be used for single OS threaded cooperative multithreading. This is, of course, not truly parallel.

**Comment by yvendruscolo** [comment]
Channel based memory sharing is great, i have worked with Clojure and work with go, that makes it a non-issue.
Would you be able to share an api proposal before implementation, so that we could discuss a bit more when time comes?
I would gladly help with api and design if possible, as janet solves many issues present in my current most loved language, Clojure.
Easy of async is great, but so easy of concurrency and parallelism, and it can attract not only users but usability.
Wish i could help more, but my ignorance limits me.
