### ISSUE TITLE
Thread marshal bug: "invalid function - env count does not match def (1 != 0)"

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/janet#778]
# janet version: `1.17.1-meson`

# Encountered behaviour

Calling `(ev/thread (fiber/new f) args :n result-chan)`, where:
- `f` is a functional closure that is intended to return a key/value pair
- `args` is an arbitrary list of arguments to `f`, including functions
- `result-chan` is a threaded channel

Puts an `[:error err]` tuple in `result-chan`.

# Expected Behaviour

The thread executes `f` on `args`, and then puts an `[:ok fib]` tuple on result-chan with the key/value pair as the last value.

# Steps to Reproduce

The function has to be rather complex to trigger this issue, so I don't have a minimal reproduction.

1. `git clone https://git.sr.ht/~subsetpark/bagatto -b ev-threads`
2. `cd bagatto`
3. `jpm -l deps`
4. `jpm -l build`
5. `cd demo/basic-site/`
5. `../../build/bag index.janet `

**Comment by bakpakin** [comment]
Looks like we can just remove the assertion here - the assertion was making sure that the number of closure environments of a closure matched the number specified in the function definition, but this isn't that important. If this info doesn't match, there will just be a runtime error and the garbage collector will be fine. The reason the assertion failed was because the function definition was only partial constructed due to the order we traverse values - the field we were checking was still set to 0.

**Comment by subsetpark** [comment]
I'm trying to test this with the new commit, but it's clearly not working because I'm getting the same error. I have the right version:

```
code-src/bagatto/demo/basic-site [ev-threads] ⊕ janet -v
1.17.1-bb405ee1
```

And try to make sure I use that interpreter when building:

```
code-src/bagatto [ev-threads] ⊕ jpm -l build --janet=`which janet` 
```

And yet I get the same error message when I run the built binary.

**Comment by bakpakin** [comment]
I doubt you are correctly running the code because that error has literally been removed from the Janet source code. Please use `jpm -l clean` and rebuild. (There is also a change in the top of tree that would cause a different issue - supervisor events from threaded channels no longer send over the entire fiber, as that is very inefficient).

**Comment by subsetpark** [comment]
Yeah, I was trying to keep this version of janet in my ~/bin directory. But I gave up that and installed it globally.

With that in place - the error doesn't show anymore!

I get a hang when running `bag` on a different project, but presumably that's an issue with my threading code. I think we can count this one closed :tada:

**Comment by subsetpark** [comment]
(The hang is from https://github.com/janet-lang/janet/issues/782)
