### ISSUE TITLE
invisible doc formatting

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#796]
In my terminal the doc strings are unreadable:

![example](https://user-images.githubusercontent.com/962885/132785742-f5af696d-7739-4478-b23d-80d66279ca34.png)

Not sure the best way to resolve this.

**Comment by uvtc** [comment]
I'm also still on v1.17.0, am on Debian (Testing), but don't have this problem in my terminal.

![image](https://user-images.githubusercontent.com/212308/132786694-03777dc0-1b31-476f-9743-1b958e689ad2.png)

**Comment by andrewchambers** [comment]
Hmm, my xresources:

```
  #define S_base03        #002b36
  #define S_base02        #073642
  #define S_base01        #586e75
  #define S_base00        #657b83
  #define S_base0         #839496
  #define S_base1         #93a1a1
  #define S_base2         #eee8d5
  #define S_base3         #fdf6e3

  *background:            S_base3
  *foreground:            S_base00
  *fadeColor:             S_base3
  *cursorColor:           S_base01
  *pointerColorBackground:S_base1
  *pointerColorForeground:S_base01

  #define S_yellow        #b58900
  #define S_orange        #cb4b16
  #define S_red           #dc322f
  #define S_magenta       #d33682
  #define S_violet        #6c71c4
  #define S_blue          #268bd2
  #define S_cyan          #2aa198
  #define S_green         #859900

  !! black dark/light
  *color0:                S_base02
  *color8:                S_base03

  !! red dark/light
  *color1:                S_red
  *color9:                S_orange

  !! green dark/light
  *color2:                S_green
  *color10:               S_base01

  !! yellow dark/light
  *color3:                S_yellow
  *color11:               S_base00

  !! blue dark/light
  *color4:                S_blue
  *color12:               S_base0

  !! magenta dark/light
  *color5:                S_magenta
  *color13:               S_violet

  !! cyan dark/light
  *color6:                S_cyan
  *color14:               S_base1

  !! white dark/light
  *color7:                S_base2
  *color15:               S_base3

  XTerm*charClass: 33:48, 37:48, 42:48, 45-47:48, 58:48, 63-64:48, 126:48
  XTerm*renderFont: true
  XTerm*faceSize: 10
  XTerm*faceName: Terminus
```

**Comment by uvtc** [comment]
I don't know how to get that config output. I'm using Xfce with the Xfce terminal.

**Comment by andrewchambers** [comment]
To be honest, I don't really understand it that much either. Basicaly this is the lowest level of config you can pass to X11. I wonder if I am missing an italic font or something.

**Comment by llmII** [comment]
If you're using XTerm, try temporarily setting it to reverse color? If the docstrings show then, then it's sort of a configuration issue (have to figure out what color is being used for what's not being shown and adjust it to a color that doesn't match background color). The other thing (and I don't know if XTerm supports this, probably does, but a few terminals do) is instead of printing italics, they'll double bold something or give it a separate color for italics (because to some people, italics are so unreadable, they prefer a different indication of italicization, italics actually used to be that bad, nowadays they're tolerably readable with increased pixel densities and better fonts).

It's pretty difficult to determine which color is being used for what from a screenshot and some config. One option I guess to determine which is effecting it is to go through each color in the config one by one and set it to `#000000` until you find which makes things readable again and then select a color that works for you. I chose #000000 because it looks like you're using light bg, dark text, for someone with the opposite I'd say go for `#FFFFFF` instead. 

The other would be to look up whats the setting for XTerm that draws italics as bold/color or something as well.

You could keep your main terminal going, then use xrdb to process your .Xresources, launch another XTerm, and see, all without modifying your current operation XTerm, so you won't end up stuck with some odd unreadable terminal (I assume outside of Janet `doc` you're able to utilize your current terminal).

That said... Github seems to append a  color dot when each color is done individually, albeit no guarantees web colors match terminal colors... so here goes:

`#002b36`
`#073642`
`#586e75`
`#657b83`
`#839496`
`#93a1a1`
`#eee8d5`
`#fdf6e3`
`#b58900`
`#cb4b16`
`#dc322f`
`#d33682`
`#6c71c4`
`#268bd2`
`#2aa198`
`#859900`

**Comment by andrewchambers** [comment]
Thanks! that resolved it, it seems like the author of this style reused base_3 is too many places.
