### ISSUE TITLE
Suspensions and exits in the event loop

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/janet#847]
Consider the following example:

```janet
(def channel (ev/chan))
(print "Waiting for something to be put in the channel...")
(def item (ev/take channel))
(print "Received " item " from the channel")
```

If saved as `example.janet` and run at the command line, the output will be:

```text
$ janet example.janet
Waiting for something to be put in the channel...
$
```

In the [Event Loop docs](https://janet-lang.org/docs/event_loop.html), it says:

> A default Janet program has a single task that will run until complete.

Based on this, I would have thought that the call to `ev/take` would cause the fiber executing the program code to suspend indefinitely. After all, it doesn't seem correct to say that the program is 'complete' when the final `print` function is never executed.

I admit that, by itself, an infinite suspension doesn't seem like something anyone would want but the reason I'm looking to achieve this behaviour is that I have a separate C thread that will call `janet_ev_post_event` when a particular event occurs and this will cause a value to be put in the channel. At the moment, this can never occur because the program ends before the event that would precipitate the call to `janet_ev_post_event` is detected.

I note that it does seem possible to achieve my desired behaviour using the following code:

```janet
(def channel (ev/thread-chan))
(print "Waiting for something to be put in the channel...")
(def item (ev/take channel))
(print "Received " item " from the channel")
```

Is a threaded channel the right approach? I don't actually want to use the channel in a different thread. While I have a separate thread that calls `janet_ev_post_event`, the callback is what will update the channel and (as I understand it) that will run in the same thread as the VM (which is the same thread as the suspended fiber).

**Comment by llmII** [comment]
If the C code or the Janet code don't operate in separate fibers, (they're in the same thread and same fiber), you are issuing an `ev/take` will *never* have data to take (the fiber has dead locked completely). If you put the Janet code in it's own fiber and C in the main fiber, or vice versa, that should cause things to work correctly I think. Death instead of dead lock is ok IMO because at both points program is doing nothing, better to do nothing without a process ID.

The reason I'd surmise that `ev/thread-chan` works is because it can't, with any certainty, guarantee there is no other thread within the Janet process, that could produce something for the thread calling `ev/take` to consume.

With fibers you can assume "hey... the event loop didn't map anything other fibers for execution on this os thread" so all `ev/chan` stuff is invalid. 

The other part is, if it's a thread, should very likely use a `ev/thread-chan`, and if it's C and Janet code on the same os thread, either the C or the Janet code needs to be in a separate fiber from the main fiber, because if you yield out to the event loop on only one os thread and one os fiber then no other code will ever execute.

**Comment by bakpakin** [comment]
Also, I should note, the mechanism here that causes threaded channels to hang while normal channels just exit normally is a reference count that is manipulated with janet_ev_dec_refcount() and janet_ev_inc_refcount(). While the reference count is non-zero, the event loop will keep going, but if it is 0 and no file descriptors are being listened to then everything will exit normally. Currently threaded channels manipulate this while normal channels do not, although for the reasons you have given it might make sense to enable this.
