### ISSUE TITLE
File open with os/open can't be read on windows and mac(with kqueue)

### ISSUE THREAD

**Issue by bakpakin** [janet-lang/janet#906]
In test suite0009.janet, there is a test that is commented out that causes some platforms to hang:

```
# Test that the stream created by os/open can be read from
(comment
  (assert-no-error "File reading 1.1"
    (def outstream (os/open "unique.txt" :wct))
    (defer (:close outstream)
      (:write outstream "123\n")
      (:write outstream "456\n"))
      
    (def outstream (os/open "unique.txt" :r))
    (defer (:close outstream)
      (assert (= "123\n456\n" (string (:read outstream :all))) "File reading 1.2"))
    (os/rm "unique.txt")))
```

Some investigation is needed on why this fails on mac and windows.

**Comment by llmII** [comment]
For kqueue, per the man page:

```
			 Vnodes
			     Returns when the file pointer is not at the end
			     of	file.  data contains the offset	from current
			     position to end of	file, and may be negative.

			     This behavior is different	from poll(2), where
			     read events are triggered for regular files un-
			     conditionally.  This event	can be triggered un-
			     conditionally by setting the NOTE_FILE_POLL flag
			     in	fflags.
```

It's likely we need to detect that we're looking at a file and set `NOTE_FILE_POLL`. Would be interesting to see how this works when per-OS event systems are removed and the poll implementation is all that's used (that'd clarify the need). In the end it's not true asynchronous file IO, files are always ready and one will get a "can read" (or in our case, at EOF eventually without certain flags) regardless of how fast/slow the disk. Event based IO on files doesn't make sense until one involves AIO (posix-ish?) or io_uring (linuxism) and there always seems to be notes about AIO being subtly different per OS.

I'm wondering why file IO via `os/open` isn't just going the blocking route tbh (pretending it's asynchronous doesn't make sense IMO).

**Comment by ishehadeh** [comment]
For windows: 

It seems like the issue is that the offset needs to be updated in the `OVERLAPPED` struct, otherwise `ReadFile` will read the same section of the file over and over again. This isn't necessary for sockets or pipes.

I'm not sure completely how to handle this. Currently, I'm signaling the stream is a file with a `JANET_STREAM_FILE` stream flag, then checking that flag is set and updating the overlapped offset in `ev_machine_read` right before calling `ReadFile`.

I'm not all that familiar with the codebase though, is there a better way to go about this?
