### ISSUE TITLE
Meson build has different symbol visibility to make build

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/janet#98]
With janetsh + meson build you will see:

[this issue](https://github.com/andrewchambers/janetsh/issues/23)

While it works fine with make.

(To be honest I think having multiple build scripts is a bit risky)

See the comment by @michaelforney in that issue for the cause.

**Comment by bakpakin** [comment]
Multiple build scripts is because C and C++ are used with many different build systems. Yeah, it's a bit risky, but I like meson because it supports really simple [subprojects](https://mesonbuild.com/Wrap-dependency-system-manual.html), which would make embedding Janet easier in the future. I haven't fully tested this yet, but it stuck out to me as a useful feature for embedding Janet in larger programs.

**Comment by bakpakin** [comment]
I believe this has been updated and addressed.
