### ISSUE TITLE
macOS make install permissions issues

### ISSUE THREAD

**Issue by masukomi** [janet-lang/janet#984]
builing from source because i didn't see a m1 release package. 

`make`, `make test`, and `make repl` all seemed to work fine. 

`make install` had issues related to 🍎 locking down all the `/usr/local/*` directories 
(macOS Monterey v12.4 on an M1 mac)

unable to create`/usr/local/include` 
```
...
mkdir -p '/usr/local/include/janet'
mkdir: /usr/local/include: Permission denied
make: *** [install] Error 1
rm build/janet.pc
```
after getting past that by using sudo 

```
mkdir -p '/usr/local/lib/janet'
mkdir: /usr/local/lib/janet: Permission denied
```

and then after that...

```
mkdir -p '/usr/local/share/man/man1/'
cp janet.1 '/usr/local/share/man/man1/'
cp: /usr/local/share/man/man1/janet.1: Permission denied
make: *** [install] Error 1
rm build/janet.pc
```

and then after that... it seemed to succeed (or at least not produce any errors)

**Comment by masukomi** [comment]
(sorry about delayed response)

> Not really sure what action I would take here.

I'm thinking a good action would be to check if the install is happening on Darwin, and then, if so, changing the install path to some standard (to Janet) location. Otherwise every mac user is going to have it installed in a different location. Superficially that's not a big problem but I figure eventually someone's going to put it somewhere weird which'll have some weird side-effect / red herring that'll just complicate debugging in some bug report. 

at the _very_ least the the build script could go "oh hey, you're on a mac. You're going to need to specify a `PREFIX`" and then exit,  rather than letting it blow up and having people's first impression be that it can't even be installed with default instructions. 


I'm a big fan of the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) myself because it doesn't clutter up my home dir with _yet another_ hidden directory.  Maybe `~/.config/janet/` or something?

**Comment by bakpakin** [comment]
The XDG paths aren't really the right place either - installing Janet should be like installing any other program. By my understanding, XDG paths are for config files.

Also, users _are_ going to have Janet installed in different places - some people (most people?) use homebrew, and will install Janet to `/opt/Cellar` or whatever that path is these days (I assume you can change it if you desire). You can have multiple installs, multiple versions, etc. The standard unix way since forever ago is PREFIX - it's arguably more standard than XDG_CONFIG_PATH and similar.

Coincidentally, I think a macports port just got merged: https://github.com/macports/macports-ports/pull/15112

**Comment by bakpakin** [comment]
A more relevant standard I think would be https://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html

Again, more linux focused than macos, but another path that is suggested is /opt/ (instead of /usr/local). I think we could detect Darwin and use /opt/ instead of /usr/local - but again, I won't want to break existing workflows like existing ports (the homebrew packaging uses meson so that is not a problem).
